import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { AdminPageHeader } from '@/components/admin/AdminShell';
import { toast } from 'sonner';

export const Route = createFileRoute('/_authenticated/admin/app-customization-live')({ component: LiveCustomizationStudio });

type Rule = { selector: string; text?: string; visible?: boolean; styles: Record<string, string> };
type Config = { page: string; theme: Record<string, unknown>; settings: Record<string, unknown>; navigation: Record<string, unknown>; elements: Rule[] };
type Page = { id: string; page_key: string; name: string; route_pattern: string };
type Selected = Rule & { tag: string; rect?: { width: number; height: number }; computed?: Record<string,string> };

const paths: Record<string,string> = { home:'/', discover:'/discover', live:'/live', rooms:'/rooms', wallet:'/wallet', recharge:'/recharge', gifts:'/gifts', ranking:'/ranking', chat:'/chat', messages:'/messages', notifications:'/notifications', settings:'/settings', login:'/login', register:'/register', splash:'/splash', 'voice-room':'/rooms', 'video-room':'/rooms', 'pk-battle':'/rooms', profile:'/profile' };
const empty = (page:string):Config => ({ page, theme:{}, settings:{}, navigation:{}, elements:[] });

export function LiveCustomizationStudio() {
  const [pages,setPages]=useState<Page[]>([]); const [pageKey,setPageKey]=useState('home'); const [config,setConfig]=useState<Config>(empty('home')); const [selected,setSelected]=useState<Selected|null>(null); const [device,setDevice]=useState<'mobile'|'tablet'|'desktop'>('mobile'); const [saving,setSaving]=useState(false); const [iframeKey,setIframeKey]=useState(0); const frame=useRef<HTMLIFrameElement>(null);
  const page=useMemo(()=>pages.find(p=>p.page_key===pageKey),[pages,pageKey]); const src=paths[pageKey] ?? '/';

  useEffect(()=>{ void loadPages(); const onMessage=(e:MessageEvent)=>{ if(e.source!==frame.current?.contentWindow || e.data?.type!=='jalwa:customization:selected') return; const p=e.data.payload as Selected; setSelected({...p, styles:p.styles??{}, selector:p.selector}); }; window.addEventListener('message',onMessage); return()=>window.removeEventListener('message',onMessage); },[]);
  useEffect(()=>{ if(page) void loadPublishedOrDraft(page); },[page?.id]);
  useEffect(()=>{ if(!frame.current?.contentWindow) return; for(const rule of config.elements) sendRule(rule); },[config.elements,iframeKey]);

  async function loadPages(){ const {data,error}=await supabase.from('app_customization_pages').select('id,page_key,name,route_pattern').order('sort_order'); if(error){toast.error(error.message);return;} setPages((data??[]) as Page[]); }
  async function loadPublishedOrDraft(p:Page){ const {data:d}=await supabase.from('app_customization_drafts').select('config').eq('page_id',p.id).eq('is_active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle(); if(d?.config){setConfig(d.config as Config);return;} const {data:v}=await supabase.from('app_customization_published').select('config').eq('page_id',p.id).eq('is_current',true).maybeSingle(); setConfig((v?.config as Config)??empty(p.page_key)); }
  function sendRule(rule:Rule){ frame.current?.contentWindow?.postMessage({type:'jalwa:customization:apply',selector:rule.selector,styles:rule.styles,text:rule.text,visible:rule.visible},'*'); }
  function patchSelected(patch:Partial<Selected>){ if(!selected)return; const next={...selected,...patch}; setSelected(next); const idx=config.elements.findIndex(x=>x.selector===selected.selector); const rule:Rule={selector:next.selector,text:next.text,visible:next.visible,styles:next.styles??{}}; setConfig(c=>({...c,elements:idx<0?[...c.elements,rule]:c.elements.map((x,i)=>i===idx?rule:x)})); sendRule(rule); }
  function style(key:string,value:string){ patchSelected({styles:{...(selected?.styles??{}),[key]:value}}); }
  async function saveDraft(){ if(!page)return; setSaving(true); const user=(await supabase.auth.getUser()).data.user; const {data:old}=await supabase.from('app_customization_drafts').select('id').eq('page_id',page.id).eq('is_active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle(); const payload={page_id:page.id,config,name:`${page.name} Live Draft`,created_by:user?.id,is_active:true}; const result=old?.id?await supabase.from('app_customization_drafts').update({config,name:payload.name}).eq('id',old.id):await supabase.from('app_customization_drafts').insert(payload); if(result.error)toast.error(result.error.message);else toast.success('Draft saved'); setSaving(false); }
  async function publish(){ if(!page)return; const user=(await supabase.auth.getUser()).data.user; const {data:last}=await supabase.from('app_customization_versions').select('version').eq('page_id',page.id).order('version',{ascending:false}).limit(1).maybeSingle(); const next=(last?.version??0)+1; const {data:v,error}=await supabase.from('app_customization_versions').insert({page_id:page.id,version:next,status:'published',config,created_by:user?.id}).select('id').single(); if(error||!v){toast.error(error?.message??'Version creation failed');return;} await supabase.from('app_customization_published').update({is_current:false}).eq('page_id',page.id).eq('is_current',true); const {error:pe}=await supabase.from('app_customization_published').insert({page_id:page.id,version_id:v.id,config,version:next,published_by:user?.id,is_current:true}); if(pe){toast.error(pe.message);return;} toast.success(`${page.name} published`); setIframeKey(k=>k+1); }
  const width=device==='mobile'?390:device==='tablet'?768:1180;
  return <div className="-m-4 min-h-[calc(100vh-64px)] bg-muted/20 md:-m-6 lg:-m-8"><AdminPageHeader title="Live App Customization" subtitle="Edit the real user-app preview from the Admin Panel. Save Draft keeps changes isolated; Publish applies the saved rules to the actual app runtime." right={<div className="flex gap-2"><button className="rounded-lg border px-3 py-2 text-sm" onClick={saveDraft} disabled={saving}>Save Draft</button><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground" onClick={publish}>Publish</button></div>} />
    <div className="flex flex-wrap gap-2 border-b bg-background p-3"><select className="rounded-lg border px-3 py-2 text-sm" value={pageKey} onChange={e=>setPageKey(e.target.value)}>{pages.map(p=><option key={p.page_key} value={p.page_key}>{p.name}</option>)}</select>{(['mobile','tablet','desktop'] as const).map(d=><button key={d} onClick={()=>setDevice(d)} className={`rounded-lg px-3 py-2 text-xs ${device===d?'bg-primary text-primary-foreground':'bg-muted'}`}>{d}</button>)}<button className="rounded-lg border px-3 py-2 text-xs" onClick={()=>setIframeKey(k=>k+1)}>Reload</button></div>
    <div className="grid min-h-[calc(100vh-150px)] lg:grid-cols-[minmax(0,1fr)_330px]"><main className="flex justify-center overflow-auto bg-zinc-950 p-5"><div style={{width,maxWidth:'100%'}} className="overflow-hidden rounded-2xl bg-background shadow-2xl"><iframe key={iframeKey} ref={frame} title="Actual App Preview" src={`${src}${src.includes('?')?'&':'?'}adminPreview=1`} className="h-[760px] w-full border-0" /></div></main>
      <aside className="border-l bg-background p-4">{selected?<div className="space-y-4"><div><b>Selected element</b><div className="mt-1 break-all text-[10px] text-muted-foreground">{selected.selector}</div></div><label className="block text-xs">Text<input className="mt-1 w-full rounded-lg border p-2" value={selected.text??''} onChange={e=>patchSelected({text:e.target.value})}/></label>{[['color','Text color'],['background-color','Background'],['font-size','Font size'],['font-weight','Font weight'],['border-radius','Radius'],['padding','Padding'],['margin','Margin'],['width','Width'],['height','Height'],['opacity','Opacity']].map(([k,l])=><label key={k} className="block text-xs">{l}<input className="mt-1 w-full rounded-lg border p-2" value={selected.styles?.[k]??''} onChange={e=>style(k,e.target.value)}/></label>)}<div className="flex gap-2"><button className="flex-1 rounded-lg border p-2 text-xs" onClick={()=>patchSelected({visible:selected.visible===false?true:false})}>{selected.visible===false?'Show':'Hide'}</button><button className="flex-1 rounded-lg border p-2 text-xs" onClick={()=>setSelected(null)}>Clear</button></div></div>:<div className="rounded-xl border p-4 text-sm"><b>Click any element</b><p className="mt-1 text-xs text-muted-foreground">The real app is shown in the center. Hover and click an element to edit it here. Changes are draft-only until Publish.</p></div>}</aside></div></div>;
}
