import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { AdminPageHeader } from '@/components/admin/AdminShell';
import { toast } from 'sonner';

export const Route = createFileRoute('/_authenticated/admin/app-customization-navigation')({ component: CustomizationNavigation });
type Item={id:string;navigation_key:string;label:string;icon:string|null;route:string|null;sort_order:number;visible:boolean;config:Record<string,unknown>};
const defaults=[['home','Home','Home','/'],['discover','Discover','Compass','/discover'],['live','Live','Radio','/live'],['rooms','Rooms','Users','/rooms'],['messages','Messages','MessageCircle','/messages'],['profile','Profile','User','/profile']];
export function CustomizationNavigation(){const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const{data,error}=await supabase.from('app_customization_navigation').select('*').order('sort_order');if(error)toast.error(error.message);else setItems((data??[])as Item[]);setLoading(false)}useEffect(()=>{void load()},[]);
 async function seed(){const user=(await supabase.auth.getUser()).data.user;for(let i=0;i<defaults.length;i++){const[dkey,label,icon,route]=defaults[i];await supabase.from('app_customization_navigation').upsert({navigation_key:dkey,label,icon,route,sort_order:i+1,visible:true,created_by:user?.id},{onConflict:'navigation_key'})}await load();toast.success('Default navigation loaded')}
 async function patch(id:string,patch:Partial<Item>){const{error}=await supabase.from('app_customization_navigation').update(patch).eq('id',id);if(error)toast.error(error.message);else setItems(x=>x.map(i=>i.id===id?{...i,...patch}:i))}
 async function add(){const user=(await supabase.auth.getUser()).data.user;const{data,error}=await supabase.from('app_customization_navigation').insert({navigation_key:`custom-${Date.now()}`,label:'New Item',icon:'Circle',route:'/',sort_order:items.length+1,visible:true,created_by:user?.id}).select('*').single();if(error)toast.error(error.message);else setItems(x=>[...x,(data as Item)])}
 async function remove(id:string){const{error}=await supabase.from('app_customization_navigation').delete().eq('id',id);if(error)toast.error(error.message);else setItems(x=>x.filter(i=>i.id!==id))}
 return <div className="-m-4 min-h-[calc(100vh-64px)] bg-muted/20 md:-m-6 lg:-m-8"><AdminPageHeader title="Navigation Builder" subtitle="Control labels, routes, icons, order and visibility for published navigation." right={<div className="flex gap-2"><button className="rounded-lg border px-3 py-2 text-sm" onClick={()=>void seed()}>Load Defaults</button><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground" onClick={()=>void add()}>+ Add Item</button></div>}/><div className="p-4 md:p-6">{loading?<div className="p-8 text-sm text-muted-foreground">Loading navigation…</div>:<div className="space-y-2">{items.map(i=><div key={i.id} className="grid gap-2 rounded-xl border bg-background p-3 md:grid-cols-[80px_1fr_1fr_120px_80px_60px]"><input className="rounded border p-2 text-xs" value={i.sort_order} type="number" onChange={e=>void patch(i.id,{sort_order:Number(e.target.value)})}/><input className="rounded border p-2 text-xs" value={i.label} onChange={e=>void patch(i.id,{label:e.target.value})}/><input className="rounded border p-2 text-xs" value={i.route??''} onChange={e=>void patch(i.id,{route:e.target.value})}/><input className="rounded border p-2 text-xs" value={i.icon??''} onChange={e=>void patch(i.id,{icon:e.target.value})}/><button className="rounded border text-xs" onClick={()=>void patch(i.id,{visible:!i.visible})}>{i.visible?'Visible':'Hidden'}</button><button className="rounded border text-xs text-destructive" onClick={()=>void remove(i.id)}>×</button></div>)}</div>}</div></div>}
