import { createFileRoute } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { AdminPageHeader } from '@/components/admin/AdminShell';
import { toast } from 'sonner';

export const Route = createFileRoute('/_authenticated/admin/app-customization-assets')({ component: CustomizationAssets });
type Asset={id:string;name:string;category:string;storage_path:string|null;public_url:string|null;mime_type:string|null;metadata:Record<string,unknown>};
const BUCKET='app-customization-assets';
export function CustomizationAssets(){
 const[assets,setAssets]=useState<Asset[]>([]);const[loading,setLoading]=useState(true);const[uploading,setUploading]=useState(false);const[category,setCategory]=useState('images');
 async function load(){setLoading(true);const{data,error}=await supabase.from('app_customization_assets').select('*').order('created_at',{ascending:false});if(error)toast.error(error.message);else setAssets((data??[])as Asset[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function upload(file:File){setUploading(true);const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'-');const path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${safe}`;const{error}=await supabase.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(error){toast.error(error.message);setUploading(false);return}const{data:url}=supabase.storage.from(BUCKET).getPublicUrl(path);const user=(await supabase.auth.getUser()).data.user;const{error:dbError}=await supabase.from('app_customization_assets').insert({name:file.name,category,storage_path:path,public_url:url.publicUrl,mime_type:file.type,metadata:{size:file.size},created_by:user?.id});if(dbError)toast.error(dbError.message);else{toast.success('Asset uploaded');await load()}setUploading(false)}
 async function remove(a:Asset){if(a.storage_path)await supabase.storage.from(BUCKET).remove([a.storage_path]);const{error}=await supabase.from('app_customization_assets').delete().eq('id',a.id);if(error)toast.error(error.message);else setAssets(x=>x.filter(v=>v.id!==a.id))}
 return <div className="-m-4 min-h-[calc(100vh-64px)] bg-muted/20 md:-m-6 lg:-m-8"><AdminPageHeader title="Customization Assets" subtitle="Upload and manage images/media used by the visual builder."/><div className="p-4 md:p-6"><div className="mb-4 flex flex-wrap items-center gap-2 rounded-xl border bg-background p-4"><select className="rounded-lg border px-3 py-2 text-sm" value={category} onChange={e=>setCategory(e.target.value)}><option value="images">Images</option><option value="icons">Icons</option><option value="banners">Banners</option><option value="backgrounds">Backgrounds</option><option value="logos">Logos</option><option value="other">Other</option></select><label className="cursor-pointer rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground">{uploading?'Uploading...':'Upload Asset'}<input type="file" className="hidden" accept="image/*,video/*" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value='' }}/></label></div>{loading?<div className="p-8 text-sm text-muted-foreground">Loading assets…</div>:<div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{assets.map(a=><div key={a.id} className="overflow-hidden rounded-xl border bg-background">{a.public_url&&a.mime_type?.startsWith('image/')?<img src={a.public_url} alt={a.name} className="aspect-square w-full object-cover"/>:<div className="flex aspect-square items-center justify-center bg-muted text-xs text-muted-foreground">{a.mime_type??'file'}</div>}<div className="p-2"><div className="truncate text-xs font-medium">{a.name}</div><div className="mt-1 flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{a.category}</span><button className="text-[10px] text-destructive" onClick={()=>void remove(a)}>Delete</button></div></div></div>)}</div>}</div></div>
}
