import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { CATALOG_GIFTS } from "@/lib/gifts";
import { isAssetUrlLike, preloadGiftVideo, resolveGiftImageUrl, resolvePlayableGiftUrl } from "@/lib/giftMedia";
import { Coins, Loader2, Send, X } from "lucide-react";
import { toast } from "sonner";
export type Gift={id:string;name:string;icon:string|null;icon_path?:string|null;emoji?:string|null;image_url:string|null;price_coins:number|null;price?:number|null;diamonds_value:number;category:string|null;animation:string|null;clip_path?:string|null;clip_type?:string|null;sound_url?:string|null;audio_url?:string|null;audio_enabled?:boolean|null;audio_volume?:number|string|null;render_config?:unknown};
export type GiftReceiver={id:string;username:string|null;avatar:string|null};
export const giftAudioEnabled=(g:Gift)=>g.audio_enabled!==false&&Number(g.audio_volume??1)>0;
export const giftAudioGain=(g:Gift)=>Math.max(0,Math.min(1,Number(g.audio_volume??1)||1));
export const giftSoundSrc=(g:Gift)=>g.audio_url??g.sound_url??null;
const price=(g:Gift|null)=>Number(g?.price_coins??g?.price??0);
const meta:Record<string,string>={popular:"🔥 Popular",classic:"🎁 Classic",romantic:"💗 Romantic",love:"💘 Love",party:"🎉 Party",luxury:"💎 Luxury",fantasy:"🦄 Fantasy",vip:"👑 VIP"};
function Preview({g}:{g:Gift}){const raw=g.image_url??g.icon_path??(isAssetUrlLike(g.icon)?g.icon:null);const img=raw?resolveGiftImageUrl(raw):null;if(img)return <img src={img} alt="" className="h-full w-full object-contain"/>;return <span className="text-4xl">{g.emoji??(isAssetUrlLike(g.icon)?"🎁":g.icon??"🎁")}</span>}
export function GiftSheet({open,onClose,roomId,receivers,onSent}:{open:boolean;onClose:()=>void;roomId:string;receivers:GiftReceiver[];onSent?:(info:{gift:Gift;targets:string[]})=>void}){
 const {profile,refresh}=useAuth(); const [balance,setBalance]=useState(0); const [roomUsers,setRoomUsers]=useState<GiftReceiver[]>(receivers); const [selected,setSelected]=useState<string[]>([]); const [all,setAll]=useState(false); const [gift,setGift]=useState<Gift|null>(null); const [qty,setQty]=useState(1); const [gifts,setGifts]=useState<Gift[]>([]); const [loading,setLoading]=useState(false);
 useEffect(()=>setRoomUsers(receivers),[receivers]);
 useEffect(()=>{if(!open||!profile?.id)return;let dead=false;const load=async()=>{const [{data:p},{data:m},{data:room}]=await Promise.all([supabase.from("profiles").select("coins").eq("id",profile.id).maybeSingle(),supabase.from("room_members").select("user_id,seat_index,seated_at").eq("room_id",roomId).order("seat_index"),supabase.from("live_rooms").select("host_id").eq("id",roomId).maybeSingle()]);if(dead)return;if(p)setBalance(Number(p.coins??0));const passed=receivers.filter(r=>r?.id);const memberIds=(m??[]).filter((x:any)=>x.user_id&&x.seated_at!==null).map((x:any)=>x.user_id);const ids=Array.from(new Set([...passed.map(r=>r.id),...memberIds,...(room?.host_id?[room.host_id]:[])])).filter(Boolean);if(!ids.length){setRoomUsers([]);return}const {data:ps}=await supabase.from("profiles").select("id,username,avatar").in("id",ids);const map=new Map((ps??[]).map(p=>[p.id,p]));setRoomUsers(ids.map(id=>{const p=map.get(id);return{id,username:p?.username??(id===room?.host_id?"Host":"User"),avatar:p?.avatar??null}}));};void load();const timer=window.setInterval(load,2000);return()=>{dead=true;window.clearInterval(timer)}},[open,profile?.id,roomId,receivers]);
 useEffect(()=>{if(!open)return;void supabase.from("gifts").select("id,name,emoji,icon,icon_path,image_url,price,price_coins,diamonds_value,category,animation,clip_path,clip_type,sound_url,audio_url,audio_enabled,audio_volume,render_config,sort_order,is_active,active").order("sort_order").then(({data,error})=>{if(error){toast.error(error.message);return}const db=((data??[]) as Gift[]).filter((g:any)=>g.is_active!==false&&g.active!==false);const ids=new Set(db.map(g=>g.id));setGifts([...db,...CATALOG_GIFTS.filter(g=>!ids.has(g.id))])})},[open]);
 const cats=useMemo(()=>Array.from(new Set(gifts.map(g=>(g.category??"classic").toLowerCase()))),[gifts]);const [cat,setCat]=useState("");useEffect(()=>{if(cats.length&&!cats.includes(cat))setCat(cats[0])},[cats,cat]);const visible=useMemo(()=>gifts.filter(g=>(g.category??"classic").toLowerCase()===cat),[gifts,cat]);
 useEffect(()=>{if(open)visible.forEach(g=>{if(g.clip_path)preloadGiftVideo(resolvePlayableGiftUrl(g.clip_path))})},[open,visible]);
 const targets=all?roomUsers.map(u=>u.id):selected;const total=price(gift)*qty*(all?Math.max(1,roomUsers.length):Math.max(1,targets.length));
 const send=async()=>{if(!gift)return;if(!targets.length){toast.error("Please select a user");return}if(total>balance){toast.error(`Insufficient coins. Balance: ${balance.toLocaleString()}`);return}setLoading(true);try{if(targets.length===1){const {error}=await supabase.rpc("send_gift",{_room_id:roomId,_receiver_id:targets[0],_gift_id:gift.id,_quantity:qty,_write_message:true});if(error)throw error}else{const {error}=await supabase.rpc("send_gift_multi",{_room_id:roomId,_receiver_ids:targets,_gift_id:gift.id,_quantity:qty});if(error)throw error}const first=roomUsers.find(u=>u.id===targets[0]);const clip=gift.clip_path?resolvePlayableGiftUrl(gift.clip_path):null;const image=resolveGiftImageUrl(gift.image_url??gift.icon_path??(isAssetUrlLike(gift.icon)?gift.icon:null));window.dispatchEvent(new CustomEvent("jalwa:gift-sent",{detail:{key:`local-${Date.now()}`,senderName:profile?.username??"Guest",senderAvatar:profile?.avatar??null,receiverId:first?.id??targets[0],receiverIds:targets,receiverName:first?.username??"User",receiverAvatar:first?.avatar??null,giftName:gift.name,giftEmoji:clip?"":gift.emoji??"🎁",giftImageUrl:image,giftClipUrl:clip??image,giftClipType:clip?gift.clip_type:(image?"image":null),coins:price(gift)*qty,diamonds:gift.diamonds_value*qty,quantity:qty,animation:gift.animation??"pop",soundUrl:giftSoundSrc(gift),audioEnabled:giftAudioEnabled(gift),audioVolume:giftAudioGain(gift),renderConfig:gift.render_config,local:true}}));await refresh();setBalance(b=>Math.max(0,b-total));toast.success(`Gift sent to ${first?.username??"selected user"}`);onSent?.({gift,targets});setGift(null);setSelected([]);setAll(false);setQty(1);onClose()}catch(e:any){toast.error(e?.message??"Unable to send gift")}finally{setLoading(false)}};
 if(!open)return null;return <div className="fixed inset-0 z-[100] bg-black/60" onClick={onClose}><div className="absolute bottom-0 left-1/2 w-full max-w-md -translate-x-1/2 overflow-hidden rounded-t-3xl border border-white/10 bg-background text-foreground shadow-2xl" onClick={e=>e.stopPropagation()}>
  <div className="flex items-center justify-between border-b px-4 py-3"><div><div className="text-sm font-black">Send Gift</div><div className="mt-1 flex items-center gap-1.5 rounded-full bg-primary/10 px-2.5 py-1 text-xs font-black"><Coins className="h-4 w-4"/> {balance.toLocaleString()} <span className="font-medium opacity-60">COINS</span></div></div><button onClick={onClose} className="rounded-full p-2 opacity-70 hover:opacity-100"><X className="h-5 w-5"/></button></div>
  <div className="border-b px-3 py-2"><div className="mb-2 flex items-center justify-between"><span className="text-[11px] font-bold opacity-70">Send to seated user / host</span><button type="button" onClick={()=>{setAll(v=>!v);setSelected([])}} disabled={!roomUsers.length} className={`rounded-full px-3 py-1 text-[10px] font-black ${all?"bg-primary text-primary-foreground":"bg-muted"}`}>ALL ({roomUsers.length})</button></div><div className="flex gap-2 overflow-x-auto pb-1">{roomUsers.length?roomUsers.map(u=>{const active=!all&&selected.includes(u.id);return <button key={u.id} type="button" onClick={()=>{setAll(false);setSelected(s=>s.includes(u.id)?s.filter(x=>x!==u.id):[...s,u.id])}} className={`flex w-16 shrink-0 flex-col items-center gap-1 rounded-xl p-1.5 ${active?"bg-primary/20 ring-2 ring-primary":"bg-muted/40"}`} title={u.id}><div className="h-11 w-11 overflow-hidden rounded-full border-2 border-white/20">{u.avatar?<img src={u.avatar} alt="" className="h-full w-full object-cover"/>:<div className="grid h-full w-full place-items-center text-sm font-black">{(u.username??"U").slice(0,1).toUpperCase()}</div>}</div><span className="w-full truncate text-center text-[9px] font-bold">{u.username??"User"}</span>{u.id&&<span className="w-full truncate text-center text-[6px] opacity-40">{u.id}</span>}</button>}) : <div className="w-full py-3 text-center text-xs opacity-50">No seated users</div>}</div></div>
  <div className="flex gap-1.5 overflow-x-auto border-b px-3 py-2">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-black ${cat===c?"bg-primary text-primary-foreground":"bg-muted"}`}>{meta[c]??c}</button>)}</div>
  <div className="grid max-h-[38dvh] grid-cols-4 gap-2 overflow-y-auto p-3">{visible.map(g=>{const active=gift?.id===g.id;return <button key={g.id} type="button" onClick={()=>setGift(active?null:g)} className={`rounded-2xl border p-2 ${active?"border-primary bg-primary/10":"border-border bg-muted/30"}`}><div className="h-16"><Preview g={g}/></div><div className="truncate text-[10px] font-bold">{g.name}</div><div className="mt-1 flex items-center justify-center gap-1 text-[10px] font-black"><Coins className="h-3 w-3"/>{price(g).toLocaleString()}</div></button>})}</div>
  <div className="flex items-center justify-between gap-2 border-t px-3 py-3"><div className="min-w-0 text-xs"><div className="truncate font-bold">{gift?.name??"Select a gift"}</div><div className="opacity-60">{targets.length?`${targets.length} recipient${targets.length>1?"s":""} · ":""}{total.toLocaleString()} coins</div></div><button type="button" disabled={!gift||!targets.length||loading||total>balance} onClick={send} className="flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-xs font-black text-primary-foreground disabled:opacity-40">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}Send</button></div>
 </div></div>;
}
