import { useEffect, useMemo, useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { CATALOG_GIFTS } from "@/lib/gifts";
import { isAssetUrlLike, preloadGiftVideo, resolveGiftImageUrl, resolvePlayableGiftUrl } from "@/lib/giftMedia";
import { getGiftAudioPrefs, playGiftAudioCue, playJalwaSignature, unlockGiftAudio } from "@/lib/giftAudio";
import { Loader2, Coins, Send } from "lucide-react";
import { toast } from "sonner";

export type Gift = {
  id: string; name: string; icon: string | null; icon_path?: string | null; emoji?: string | null;
  image_url: string | null; price_coins: number | null; price?: number | null; diamonds_value: number;
  category: string | null; animation: string | null; clip_path?: string | null; clip_type?: string | null;
  sound_url?: string | null; audio_url?: string | null; audio_enabled?: boolean | null;
  audio_volume?: number | string | null; render_config?: unknown;
};
export function giftAudioEnabled(g: { audio_enabled?: boolean | null; audio_volume?: number | string | null }) { return g.audio_enabled !== false && Number(g.audio_volume ?? 1) > 0; }
export function giftAudioGain(g: { audio_volume?: number | string | null }) { const v=Number(g.audio_volume ?? 1); return Number.isFinite(v)?Math.max(0,Math.min(1,v)):1; }
export function giftSoundSrc(g: { audio_url?: string | null; sound_url?: string | null }) { return g.audio_url ?? g.sound_url ?? null; }
export type GiftReceiver = { id: string; username: string | null; avatar: string | null };
type Tier="small"|"premium"|"vip"; const tierOf=(p:number):Tier=>p<=300?"small":p<2000?"premium":"vip";
const CATEGORY_META:Record<string,{label:string;emoji:string}>={popular:{label:"Popular",emoji:"🔥"},classic:{label:"Classic",emoji:"🎁"},romantic:{label:"Romantic",emoji:"💗"},love:{label:"Love",emoji:"💘"},party:{label:"Party",emoji:"🎉"},luxury:{label:"Luxury",emoji:"💎"},fantasy:{label:"Fantasy",emoji:"🦄"},vip:{label:"VIP",emoji:"👑"}};
const catLabel=(k:string)=>CATEGORY_META[k]?.label??(k.charAt(0).toUpperCase()+k.slice(1)); const catEmoji=(k:string)=>CATEGORY_META[k]?.emoji??"🎁";
const LOVABLE_ASSET_ORIGIN="https://cloud-to-soul.lovable.app";
const ROYAL_ROSE_MP4_URL=`${LOVABLE_ASSET_ORIGIN}/__l5e/assets-v1/82be6f35-cb0c-44fc-8232-8514da26b101/royal-rose.mp4`;
const ROYAL_ROSE_THUMB_URL=`${LOVABLE_ASSET_ORIGIN}/__l5e/assets-v1/fb1418b5-4aaa-4f54-8ea2-b411da08f604/royal-rose.png`;
const isRoyalRoseGift=(n:string|null|undefined)=>{const x=(n??"").toLowerCase().replace(/[^a-z]+/g," ").trim();return x==="royal rose"||(x.includes("royal")&&x.includes("rose"));};
function GiftPreview({gift,large=false}:{gift:Gift;large?:boolean}){const cls="h-full w-full object-contain drop-shadow-[0_3px_10px_rgba(0,0,0,0.5)]";if(isRoyalRoseGift(gift.name))return <img src={ROYAL_ROSE_THUMB_URL} alt="" className={cls} loading="lazy"/>; const video=(u?:string|null)=>!!u&&/\.(mp4|webm)(\?|$)/i.test(u); const c=[gift.image_url,gift.icon_path,isAssetUrlLike(gift.icon)?gift.icon:null].filter((u):u is string=>!!u&&!video(u)); const t=c.length?resolveGiftImageUrl(c[0]):null;if(t)return <img src={t} alt="" className={cls} loading="lazy"/>;if(gift.clip_path&&gift.clip_type==="svg")return <img src={resolveGiftImageUrl(gift.clip_path)??gift.clip_path} alt="" className={cls} loading="lazy"/>;const raw=gift.icon??gift.emoji??"";const bad=!raw||isAssetUrlLike(raw)||raw.length>4||/[<>{}\/\\]/.test(raw);return <span className={`${large?"text-5xl":"text-4xl"} leading-none`}>{bad?"🎁":raw}</span>;}
export function GiftSheet({open,onClose,roomId,receivers,onSent}:{open:boolean;onClose:()=>void;roomId:string;receivers:GiftReceiver[];onSent?:(info:{gift:Gift;targets:string[]})=>void}){
 const {profile,refresh}=useAuth();const qc=useQueryClient();const[selectedGift,setSelectedGift]=useState<Gift|null>(null);const[receiverId,setReceiverId]=useState<string|null>(receivers[0]?.id??null);const[sendToAll,setSendToAll]=useState(false);const[qty,setQty]=useState(1);const[activeCategory,setActiveCategory]=useState("");const[confirmOpen,setConfirmOpen]=useState(false);const[pageIndex,setPageIndex]=useState(0);
 const gifts=useQuery({queryKey:["gifts"],queryFn:async()=>{const{data,error}=await supabase.from("gifts").select("id,name,emoji,icon,icon_path,image_url,price,price_coins,diamonds_value,category,animation,clip_path,clip_type,sound_url,audio_url,audio_enabled,audio_volume,render_config,sort_order,is_active,active").order("sort_order");if(error)throw error;const rows=(data??[]) as (Gift&{sort_order?:number;is_active?:boolean;active?:boolean})[];const db=rows.filter(g=>g.is_active!==false&&g.active!==false);const ids=new Set(db.map(g=>g.id));return [...db,...CATALOG_GIFTS.filter(g=>!ids.has(g.id))];},enabled:open});
 const topGifter=useQuery({queryKey:["room_top_gifter",roomId],queryFn:async()=>{const{data,error}=await supabase.rpc("room_top_gifters",{_room_id:roomId,_limit:1});if(error)throw error;return data?.[0]??null;},enabled:open});
 const price=(g:Gift|null)=>(g?.price_coins??g?.price??0) as number;
 const categoryList=useMemo(()=>{const c=new Map<string,number>();(gifts.data??[]).forEach(g=>{const k=(g.category??"").trim().toLowerCase()||"classic";c.set(k,(c.get(k)??0)+1);});const order=["popular","classic","romantic","love","party","luxury","fantasy","vip"];return [...order.filter(k=>c.has(k)),...Array.from(c.keys()).filter(k=>!order.includes(k)).sort()];},[gifts.data]);
 useEffect(()=>{if(categoryList.length&&!categoryList.includes(activeCategory))setActiveCategory(categoryList[0]);},[categoryList,activeCategory]);
 const visibleGifts=useMemo(()=>{const a=(gifts.data??[]).filter(g=>((g.category??"").trim().toLowerCase()||"classic")===activeCategory);return a.slice().sort((x,y)=>price(x)-price(y));},[gifts.data,activeCategory]);
 const pages=useMemo(()=>{const out:Gift[][]=[];for(let i=0;i<visibleGifts.length;i+=8)out.push(visibleGifts.slice(i,i+8));return out.length?out:[[]];},[visibleGifts]);
 useEffect(()=>setPageIndex(0),[activeCategory]);
 const giftVideoUrl=(g:Gift|null)=>g?.clip_path&&["mp4","webm","svga"].includes(g.clip_type??"")?resolvePlayableGiftUrl(g.clip_path):null;
 const giftThumbUrl=(g:Gift|null)=>g?resolveGiftImageUrl(g.image_url??g.icon_path??(isAssetUrlLike(g.icon)?g.icon:null)):null;
 useEffect(()=>{if(open){CATALOG_GIFTS.forEach(g=>preloadGiftVideo(g.clip_path));}},[open]);useEffect(()=>{if(open)visibleGifts.forEach(g=>preloadGiftVideo(giftVideoUrl(g)));},[open,visibleGifts]);useEffect(()=>{if(selectedGift)preloadGiftVideo(giftVideoUrl(selectedGift));},[selectedGift]);
 useEffect(()=>{if(!open||sendToAll)return;if(receiverId&&receivers.some(r=>r.id===receiverId))return;setReceiverId(receivers[0]?.id??null);},[open,receiverId,receivers,sendToAll]);
 const send=useMutation({mutationFn:async({gift,targets,quantity}:{gift:Gift;targets:string[];quantity:number})=>{if(!targets.length)throw Error("Pick a receiver");if(targets.length===1){const{error}=await supabase.rpc("send_gift",{_room_id:roomId,_receiver_id:targets[0],_gift_id:gift.id,_quantity:quantity});if(error)throw error;}else{const{error}=await supabase.rpc("send_gift_multi",{_room_id:roomId,_receiver_ids:targets,_gift_id:gift.id,_quantity:quantity} as any);if(error)throw error;}return true;},onSuccess:async()=>{await refresh();qc.invalidateQueries({queryKey:["wallet_tx"]});setSelectedGift(null);setQty(1);},onError:(e:Error)=>toast.error(e.message)});
 if(!open)return null;const totalCost=price(selectedGift)*qty*(sendToAll?Math.max(1,receivers.length):1);const canAfford=(profile?.coins??0)>=totalCost;
 const performSend=()=>{if(!selectedGift||send.isPending)return;const targets=sendToAll?receivers.map(r=>r.id):receiverId?[receiverId]:[];if(!targets.length)return toast.error("Pick a receiver");const first=receivers.find(r=>r.id===targets[0]);const royal=isRoyalRoseGift(selectedGift.name);const clip=royal?ROYAL_ROSE_MP4_URL:giftVideoUrl(selectedGift);const thumb=royal?ROYAL_ROSE_THUMB_URL:giftThumbUrl(selectedGift);window.dispatchEvent(new CustomEvent("jalwa:gift-sent",{detail:{key:`local-${selectedGift.id}-${Date.now()}`,senderName:profile?.username??"Guest",senderAvatar:profile?.avatar??null,receiverId:first?.id??null,receiverIds:targets,receiverName:first?.username??"Host",receiverAvatar:first?.avatar??null,giftName:selectedGift.name,giftEmoji:clip?"":selectedGift.emoji??(isAssetUrlLike(selectedGift.icon)?"":selectedGift.icon)??"🎁",giftImageUrl:thumb,giftClipUrl:clip??thumb,giftClipType:clip?selectedGift.clip_type:(thumb?"image":null),coins:price(selectedGift)*qty,diamonds:selectedGift.diamonds_value*qty,quantity:qty,animation:selectedGift.animation??"pop",soundUrl:giftSoundSrc(selectedGift),audioEnabled:giftAudioEnabled(selectedGift),audioVolume:giftAudioGain(selectedGift),renderConfig:selectedGift.render_config,local:true}}));onClose();send.mutate({gift:selectedGift,targets,quantity:qty});onSent?.({gift:selectedGift,targets});};
 const handleSend=()=>{if(!selectedGift||send.isPending)return;if(!canAfford)return toast.error("Not enough coins");if(tierOf(price(selectedGift))==="vip"){setConfirmOpen(true);return;}performSend();};
 return <div className="fixed inset-0 z-50 flex flex-col justify-end bg-black/50" onClick={onClose} data-jalwa-overlay="true"><div onClick={e=>e.stopPropagation()} className="relative mx-auto flex h-[46dvh] max-h-[420px] min-h-[340px] w-full max-w-md flex-col overflow-hidden rounded-t-[2rem] border-t-4 border-[var(--theme-primary,#7c3aed)] bg-[var(--theme-surface,#0f041e)] text-[var(--theme-text,#fff)] shadow-[0_-12px_50px_rgba(124,58,237,.35)]" style={{paddingBottom:"calc(env(safe-area-inset-bottom) + .25rem)",contain:"layout paint",fontFamily:"'Outfit',system-ui,sans-serif"}}>
 <div className="pointer-events-none absolute inset-0 opacity-[.04]" style={{backgroundImage:"radial-gradient(circle,currentColor 1px,transparent 1px)",backgroundSize:"18px 18px"}}/><div className="mx-auto mt-2 mb-1 h-1 w-12 rounded-full bg-current opacity-25"/>
 <div className="flex items-center justify-between gap-2 px-3 py-1.5"><div className="flex min-w-0 items-center gap-1.5 rounded-full border border-current/10 bg-black/15 py-1 pl-1 pr-2">{!sendToAll&&receivers.slice(0,4).map(r=><button key={r.id} onClick={()=>{setSendToAll(false);setReceiverId(r.id)}} aria-label={r.username??"user"} className={`grid h-7 w-7 shrink-0 place-items-center overflow-hidden rounded-full p-[1.5px] transition ${receiverId===r.id?"ring-2 ring-[var(--theme-accent,#ff2d87)]":"opacity-60"}`}>{r.avatar?<img src={r.avatar} alt="" className="h-full w-full rounded-full object-cover"/>:<span className="text-[9px] font-bold">{(r.username??"?")[0]?.toUpperCase()}</span>}</button>)}<span className="ml-1 truncate text-[10px] font-bold uppercase tracking-wider opacity-80">{sendToAll?`All (${receivers.length})`:`→ ${(receivers.find(r=>r.id===receiverId)?.username??"Host").slice(0,10)}`}</span></div>{receivers.length>1&&<button onClick={()=>setSendToAll(v=>!v)} className={`rounded-full px-3 py-1 text-[10px] font-black uppercase ${sendToAll?"bg-[var(--theme-primary,#7c3aed)] text-white":"bg-black/15 opacity-80"}`}>{sendToAll?"All Seated":"All"}</button>}</div>
 <div className="scrollbar-hide relative flex shrink-0 items-center gap-1.5 overflow-x-auto border-b border-current/10 px-3 pb-1.5">{categoryList.map(c=><button key={c} onClick={()=>setActiveCategory(c)} className={`flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1 text-[10px] font-black uppercase tracking-wider transition ${activeCategory===c?"bg-[var(--theme-primary,#7c3aed)] text-white shadow-lg":"bg-black/10 opacity-60"}`}><span>{catEmoji(c)}</span><span>{catLabel(c)}</span></button>)}</div>
 <div className="relative min-h-0 flex-1">{gifts.isLoading?<div className="py-6 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin opacity-40"/></div>:<div className="scrollbar-hide flex h-full w-full snap-x snap-mandatory overflow-x-auto overflow-y-hidden scroll-smooth" onScroll={e=>{const el=e.currentTarget;const i=Math.round(el.scrollLeft/Math.max(1,el.clientWidth));if(i!==pageIndex)setPageIndex(i);}}>{pages.map((pg,pi)=><div key={pi} className="grid h-full w-full shrink-0 snap-center grid-cols-4 grid-rows-2 gap-2 px-3 py-2">{pg.map(g=>{const selected=selectedGift?.id===g.id;return <button key={g.id} onClick={()=>{unlockGiftAudio();if(selected)handleSend();else setSelectedGift(g)}} onPointerDown={()=>preloadGiftVideo(giftVideoUrl(g))} className={`group relative flex min-h-0 flex-col items-center justify-between overflow-hidden rounded-2xl border p-1.5 transition active:scale-[.97] ${selected?"border-[var(--theme-accent,#ff2d87)] bg-[var(--theme-primary,#7c3aed)]/15 shadow-[0_0_18px_rgba(255,45,135,.28)]":"border-current/10 bg-black/10 hover:bg-black/15"}`}><div className="flex min-h-0 w-full flex-1 items-center justify-center overflow-hidden rounded-xl"><GiftPreview gift={g}/></div><div className="mt-1 w-full text-center"><div className="truncate px-0.5 text-[9px] font-semibold opacity-65">{g.name}</div><div className="flex items-center justify-center gap-1"><span className="h-1.5 w-1.5 rounded-full bg-[var(--theme-gold,#f5c542)]"/><span className="text-[11px] font-black text-[var(--theme-gold,#f5c542)]">{price(g)>=1000?`${(price(g)/1000).toFixed(price(g)%1000===0?0:1)}k`:price(g)}</span></div></div>{selected&&<span className="absolute right-1 top-1 rounded-full bg-[var(--theme-accent,#ff2d87)] px-1.5 py-0.5 text-[8px] font-black uppercase text-white">Pick</span>}</button>})}{pg.length<8&&Array.from({length:8-pg.length}).map((_,i)=><div key={`empty-${i}`} className="rounded-2xl border border-current/5 bg-black/5"/>)}</div>)}</div>}</div>
 {pages.length>1&&<div className="flex shrink-0 items-center justify-center gap-1 pb-1">{pages.map((_,i)=><span key={i} className={`h-1 rounded-full transition-all ${i===pageIndex?"w-4 bg-[var(--theme-accent,#ff2d87)]":"w-1 bg-current opacity-20"}`}/>)}</div>}
 <div className="flex shrink-0 items-center gap-2 border-t border-current/10 bg-black/10 px-3 py-2"><Link to="/recharge" onClick={onClose} className="flex items-center gap-1.5"><div className="flex flex-col leading-none"><div className="flex items-center gap-1"><span className="h-2.5 w-2.5 rounded-full bg-[var(--theme-gold,#f5c542)]"/><span className="text-sm font-black">{(profile?.coins??0).toLocaleString()}</span></div><span className="mt-0.5 text-[8px] font-bold uppercase tracking-[2px] opacity-30">Coins</span></div><span className="grid h-7 w-7 place-items-center rounded-lg bg-[var(--theme-primary,#7c3aed)] text-base font-black text-white">+</span></Link><div className="flex items-center rounded-lg border border-current/10 bg-black/10 p-0.5">{[1,10,99].map(n=><button key={n} onClick={()=>setQty(n)} className={`min-w-[26px] rounded-md px-1.5 py-1 text-[10px] font-black ${qty===n?"bg-white text-black":"opacity-60"}`}>x{n}</button>)}</div><button onClick={handleSend} disabled={!selectedGift||(!sendToAll&&!receiverId)||!canAfford||send.isPending} className="ml-auto flex h-10 flex-1 items-center justify-center rounded-xl bg-[var(--theme-primary,#7c3aed)] px-4 text-white disabled:bg-black/10 disabled:text-current disabled:opacity-30">{send.isPending?<Loader2 className="h-4 w-4 animate-spin"/>:<span className="flex items-center gap-1.5 text-[12px] font-black uppercase italic tracking-widest"><Send className="h-3.5 w-3.5"/>Send</span>}</button></div>
 {selectedGift&&!canAfford&&<p className="px-4 pb-1 text-center text-[10px] font-bold text-[var(--theme-accent,#ff2d87)]">Not enough coins. <Link to="/recharge" onClick={onClose} className="underline">Recharge</Link></p>}
 </div>{confirmOpen&&selectedGift&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/70 px-6" onClick={()=>setConfirmOpen(false)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-xs rounded-2xl border border-[var(--theme-primary,#7c3aed)]/60 bg-[var(--theme-surface,#0f041e)] p-5 text-white"><div className="text-center"><div className="text-[10px] font-black uppercase tracking-[3px] text-[var(--theme-gold,#ffd76a)]">👑 VIP Gift</div><div className="mt-1 text-lg font-black">Confirm Send</div></div><div className="mt-4 flex items-center gap-3 rounded-xl bg-black/20 p-3"><div className="h-14 w-14 shrink-0 overflow-hidden rounded-lg"><GiftPreview gift={selectedGift}/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{selectedGift.name}</div><div className="mt-0.5 text-[10px] opacity-50">x{qty}{sendToAll?` · ${Math.max(1,receivers.length)} receivers`:""}</div></div></div><div className="mt-3 space-y-1.5 rounded-xl bg-black/10 p-3 text-[12px]"><div className="flex justify-between opacity-70"><span>Total cost</span><span className="font-black">{totalCost.toLocaleString()}</span></div><div className="flex justify-between opacity-70"><span>Your balance</span><span className="font-bold">{(profile?.coins??0).toLocaleString()}</span></div></div><div className="mt-4 flex gap-2"><button onClick={()=>setConfirmOpen(false)} className="flex-1 rounded-xl bg-black/10 py-2.5 text-[12px] font-black">Cancel</button><button onClick={()=>{setConfirmOpen(false);performSend()}} className="flex-1 rounded-xl bg-[var(--theme-primary,#7c3aed)] py-2.5 text-[12px] font-black text-white">Confirm</button></div></div></div>}</div>;
}