import React, { useCallback, useMemo, useState } from 'react';

type Device = 'mobile' | 'tablet' | 'desktop';
type Node = { id:string; type:string; name:string; x:number; y:number; width:number; height:number; text?:string; children?:string[]; style?:Record<string,unknown> };
type Page = { id:string; name:string; root:string[] };

type Project = { pages:Page[]; components:Record<string,Node>; settings:{grid:number; snap:boolean} };

const library = ['Text','Heading','Button','Image','Video','Icon','Avatar','Card','Input','Search','Navbar','Bottom navigation','Tabs','Modal','Popup','Banner','List','Grid','Container','Section','Divider','Spacer'];

const initial:Project = { pages:[{id:'home',name:'Home',root:[]}],components:{},settings:{grid:8,snap:true} };

function uid(){return Math.random().toString(36).slice(2,10)}
function makeNode(type:string, n:number):Node { const id=uid(); return {id,type,name:`${type} ${n}`,x:24,y:24,width:type==='Button'?120:280,height:type==='Spacer'?24:type==='Heading'?48:56,text:['Text','Heading','Button','Navbar','Bottom navigation','Tabs','Banner'].includes(type)?type:'',style:{background:type==='Button'?'#ec009c':'transparent',borderRadius:12,padding:12,fontSize:type==='Heading'?24:16,color:'#fff'}} }

export default function AppBuilderV3(){
 const [project,setProject]=useState<Project>(()=>{try{return JSON.parse(localStorage.getItem('jalwa-builder-v1')||'')}catch{return initial}});
 const [pageId,setPageId]=useState('home'); const [selected,setSelected]=useState<string|null>(null); const [device,setDevice]=useState<Device>('mobile'); const [history,setHistory]=useState<Project[]>([]); const [future,setFuture]=useState<Project[]>([]); const [grid,setGrid]=useState(true); const [preview,setPreview]=useState(false);
 const page=project.pages.find(p=>p.id===pageId)!; const nodes=page.root.map(id=>project.components[id]).filter(Boolean); const sel=selected?project.components[selected]:null;
 const commit=useCallback((next:Project)=>{setHistory(h=>[...h,project].slice(-30));setFuture([]);setProject(next)},[project]);
 const update=(patch:Partial<Node>)=>{if(!sel)return;commit({...project,components:{...project.components,[sel.id]:{...sel,...patch}}})};
 const add=(type:string)=>{const n=makeNode(type,nodes.length+1); const p={...project,components:{...project.components,[n.id]:n},pages:project.pages.map(x=>x.id===pageId?{...x,root:[...x.root,n.id]}:x)};commit(p);setSelected(n.id)};
 const remove=()=>{if(!sel)return;commit({...project,components:Object.fromEntries(Object.entries(project.components).filter(([id])=>id!==sel.id)),pages:project.pages.map(x=>({...x,root:x.root.filter(id=>id!==sel.id)}))});setSelected(null)};
 const duplicate=()=>{if(!sel)return;const n={...sel,id:uid(),name:sel.name+' Copy',x:sel.x+16,y:sel.y+16};commit({...project,components:{...project.components,[n.id]:n},pages:project.pages.map(x=>x.id===pageId?{...x,root:[...x.root,n.id]}:x)});setSelected(n.id)};
 const save=()=>localStorage.setItem('jalwa-builder-v1',JSON.stringify(project));
 const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[project,...f]);setHistory(h=>h.slice(0,-1));setProject(prev)};
 const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,project]);setFuture(f=>f.slice(1));setProject(next)};
 const exportJson=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));a.download='jalwa-app-project.json';a.click()};
 const importJson=(file:File)=>{const r=new FileReader();r.onload=()=>{try{commit(JSON.parse(String(r.result)))}catch{alert('Invalid project JSON')}};r.readAsText(file)};
 if(preview)return <div className="min-h-screen bg-black text-white p-4"><button className="mb-4 rounded-lg bg-pink-600 px-4 py-2" onClick={()=>setPreview(false)}>Exit Preview</button><div className="relative mx-auto overflow-hidden rounded-[32px] bg-zinc-950" style={{width:device==='mobile'?390:device==='tablet'?768:'100%',minHeight:700}}>{nodes.map(n=><div key={n.id} className="absolute" style={{left:n.x,top:n.y,width:n.width,height:n.height,...n.style as any}}>{n.type==='Image'?<img className="h-full w-full object-cover rounded-inherit" src={String(n.style?.src||'')} />:n.text}</div>)}</div></div>
 return <div className="flex h-[calc(100vh-0px)] min-h-[700px] bg-[#09070b] text-white">
  <aside className="w-64 shrink-0 border-r border-white/10 p-3 overflow-y-auto"><h2 className="px-2 py-3 text-lg font-bold">Components</h2>{library.map(x=><button key={x} onClick={()=>add(x)} className="mb-2 w-full rounded-lg border border-white/10 bg-white/[.03] px-3 py-2 text-left hover:bg-pink-500/20">＋ {x}</button>)}</aside>
  <main className="flex min-w-0 flex-1 flex-col"><header className="flex items-center gap-2 border-b border-white/10 p-3"><b>Jalwa App Builder</b><div className="ml-auto flex gap-2"><button onClick={undo}>↶</button><button onClick={redo}>↷</button><button onClick={()=>setGrid(!grid)}>Grid</button><button onClick={save}>Save</button><button onClick={exportJson}>Export</button><label className="cursor-pointer rounded bg-white/10 px-3 py-1">Import<input hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importJson(e.target.files[0])}/></label><button onClick={()=>setPreview(true)} className="rounded bg-pink-600 px-3 py-1">Preview</button></div></header>
   <div className="flex items-center justify-center gap-2 border-b border-white/10 p-2">{(['mobile','tablet','desktop'] as Device[]).map(d=><button key={d} onClick={()=>setDevice(d)} className={`rounded px-3 py-1 ${device===d?'bg-pink-600':'bg-white/5'}`}>{d}</button>)}<button onClick={()=>setProject({...project,settings:{...project.settings,snap:!project.settings.snap}})} className="rounded bg-white/5 px-3 py-1">Snap {project.settings.snap?'On':'Off'}</button></div>
   <div className="flex flex-1 items-start justify-center overflow-auto p-8" onDragOver={e=>e.preventDefault()}>{<div className="relative overflow-hidden rounded-[28px] border border-white/20 bg-zinc-950 shadow-2xl" style={{width:device==='mobile'?390:device==='tablet'?768:1000,minHeight:700,backgroundImage:grid?'linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px)':'none',backgroundSize:`${project.settings.grid}px ${project.settings.grid}px`}}>{nodes.map(n=><div key={n.id} draggable onClick={e=>{e.stopPropagation();setSelected(n.id)}} onDragEnd={e=>{const r=(e.currentTarget.parentElement as HTMLElement).getBoundingClientRect();let x=e.clientX-r.left-n.width/2,y=e.clientY-r.top-n.height/2;if(project.settings.snap){x=Math.round(x/project.settings.grid)*project.settings.grid;y=Math.round(y/project.settings.grid)*project.settings.grid}update({x:Math.max(0,x),y:Math.max(0,y)})}} className={`absolute select-none border ${selected===n.id?'border-pink-500 ring-2 ring-pink-500/30':'border-transparent'}`} style={{left:n.x,top:n.y,width:n.width,height:n.height,...n.style as any}}>{n.text}<span className="absolute -bottom-1 -right-1 h-3 w-3 cursor-se-resize bg-pink-500" onPointerDown={e=>{e.stopPropagation();const sx=e.clientX,sy=e.clientY,sw=n.width,sh=n.height;const move=(ev:PointerEvent)=>update({width:Math.max(20,sw+ev.clientX-sx),height:Math.max(20,sh+ev.clientY-sy)});const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}} /></div>)}</div>}</div>
  </main>
  <aside className="w-80 shrink-0 border-l border-white/10 p-3 overflow-y-auto"><h2 className="text-lg font-bold">Properties</h2>{sel?<><div className="grid grid-cols-2 gap-2 mt-3">{(['x','y','width','height'] as const).map(k=><label key={k} className="text-xs">{k}<input type="number" value={sel[k]} onChange={e=>update({[k]:Number(e.target.value)} as any)} className="mt-1 w-full rounded bg-white/5 p-2"/></label>)}</div><label className="mt-3 block text-xs">Text<input value={sel.text||''} onChange={e=>update({text:e.target.value})} className="mt-1 w-full rounded bg-white/5 p-2"/></label><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={duplicate} className="rounded bg-white/10 p-2">Duplicate</button><button onClick={remove} className="rounded bg-red-500/20 p-2">Delete</button></div></>:<p className="mt-3 text-sm text-white/50">Select a component.</p>}<h2 className="mt-6 text-lg font-bold">Layers</h2>{nodes.map(n=><button key={n.id} onClick={()=>setSelected(n.id)} className={`mt-2 w-full rounded p-2 text-left ${selected===n.id?'bg-pink-600':'bg-white/5'}`}>{n.name}</button>)}</aside>
 </div>
}
