import type { AppComponentNode, AppPageConfig, ComponentStyle, DeviceKind } from "./schema";
import { flattenLiveRoomRegistry } from "./live-room-registry";
import { getLiveRoomStateConfig } from "./live-room-state-config";

type LiveKind = "voice-room" | "video-room" | "pk-battle";
const selectors: Record<string,string[]>={"room-header":["[data-room-header]","header","[class*='room-header']"],"room-info":["[data-room-info]","[class*='room-info']","[class*='roomInfo']"],"room-chat":["[data-room-chat]","[class*='room-chat']","textarea","input[placeholder*='message' i]","input[placeholder*='chat' i]"],"room-gifts":["[data-gift-notification]","[class*='gift-notification']","[class*='gift-animation']"],"room-announcement":["[data-room-announcement]","[class*='announcement']"],"room-controls":["[data-room-controls]","[class*='room-controls']"],"bottom-sheet":["[data-bottom-sheet]","[role='dialog'][data-state]","[class*='bottom-sheet']"],"voice-seat":["[data-seat]","[data-seat-id]","[class*='seat-']","[class*='seat ']"],"host-card":["[data-host-card]","[class*='host-card']"],waveform:["[data-waveform]","canvas[class*='wave']","[class*='waveform']"],"room-audio-controls":["[data-room-audio-controls]","[data-room-controls]","[class*='voice-controls']","[class*='audio-controls']"],"video-tile":["[data-video-tile]","video","[class*='video-tile']","[class*='participant-video']"],"video-grid":["[data-video-grid]","[class*='video-grid']"],"room-controls":["[data-room-controls]","[class*='room-controls']","[class*='video-controls']"],"camera-control":["button[aria-label*='camera' i]","button[title*='camera' i]"],"active-speaker":["[data-active-speaker]","[class*='active-speaker']"],"pk-team-a":["[data-pk-team='a']","[data-team='a']","[class*='team-a']"],"pk-team-b":["[data-pk-team='b']","[data-team='b']","[class*='team-b']"],"pk-score":["[data-pk-score]","[class*='pk-score']","[class*='score']"],"pk-vs":["[data-pk-vs]","[class*='pk-vs']","[class*='vs-graphic']"],"pk-timer":["[data-pk-timer]","[class*='pk-timer']","[class*='battle-timer']"],"pk-progress":["[data-pk-progress]","[class*='pk-progress']","[class*='battle-progress']"],"winner-overlay":["[data-winner-overlay]","[class*='winner-overlay']"],"bottom-navigation":["[data-bottom-nav]","nav[aria-label*='bottom' i]","[class*='bottom-nav']"]};
function isRoomPath(p:string){return p.includes("/room/")||p.includes("/pk/")||p.includes("/voice-room")||p.includes("/video-room")}
function unique(e:Element[]){return Array.from(new Set(e))}
function findElements(t:string){const r:Element[]=[];for(const s of selectors[t]??[]){try{r.push(...Array.from(document.querySelectorAll(s)))}catch{}}return unique(r)}
function deviceKind():DeviceKind{const w=window.innerWidth;return w<640?"mobile":w<1024?"tablet":"desktop"}
function responsiveStyle(node:AppComponentNode,device:DeviceKind):ComponentStyle|undefined{return node.responsive?.[device]?.style??node.style}
function applyStyle(target:HTMLElement,style:ComponentStyle|undefined){if(!style)return;const{spacing,shadows,gradient,...css}=style as ComponentStyle;for(const[k,v]of Object.entries(css)){if(v==null||k==="x"||k==="y")continue;try{(target.style as unknown as Record<string,string|number>)[k]=v as string|number}catch{}}if(style.x!==undefined||style.y!==undefined)target.style.translate=`${style.x??0}px ${style.y??0}px`;if(spacing){target.style.marginTop=spacing.top==null?"":String(spacing.top);target.style.marginRight=spacing.right==null?"":String(spacing.right);target.style.marginBottom=spacing.bottom==null?"":String(spacing.bottom);target.style.marginLeft=spacing.left==null?"":String(spacing.left)}if(shadows?.length&&!style.boxShadow)target.style.boxShadow=shadows.map(s=>`${s.x}px ${s.y}px ${s.blur}px ${s.spread??0}px ${s.color}`).join(", ");if(gradient?.stops?.length&&!style.background){const a=gradient.angle??180;target.style.background=`${gradient.type}-gradient(${a}deg, ${gradient.stops.map(s=>`${s.color} ${s.position}%`).join(", ")})`}}
function applyNode(target:Element,node:AppComponentNode,device:DeviceKind){if(!(target instanceof HTMLElement))return;target.setAttribute("data-jalwa-live-node",node.id);target.setAttribute("data-jalwa-live-component",String(node.props?.componentType??""));target.setAttribute("data-jalwa-live-component-id",String(node.props?.componentId??""));target.setAttribute("data-jalwa-live-instance-index",String(node.props?.instanceIndex??0));const responsive=node.responsive?.[device];target.toggleAttribute("data-jalwa-live-hidden",node.visible===false||responsive?.visible===false);if(node.visible===false||responsive?.visible===false)target.style.display="none";else{target.style.display="";applyStyle(target,responsiveStyle(node,device))}}
function componentKind(p:string):LiveKind{return p.includes("/pk/")?"pk-battle":p.includes("video")?"video-room":"voice-room"}
function registryKind(k:LiveKind){return k==="voice-room"?"voice":k==="video-room"?"video":"pk"}
function stableKey(node:AppComponentNode){return `${String(node.props?.componentId??"")}:${Number(node.props?.instanceIndex??0)}`}

export function bindLiveRoomComponents(pathname:string,config?:AppPageConfig){if(typeof document==="undefined"||!isRoomPath(pathname))return()=>undefined;const kind=componentKind(pathname),root=document.querySelector("main")??document.body;root.setAttribute("data-jalwa-live-room",kind);const registry=new Map(flattenLiveRoomRegistry(registryKind(kind)).slice(1).map(i=>[i.id,i]));const studioPreview=new URLSearchParams(window.location.search).get("studioPreview")==="1";const bound=new WeakMap<Element,string>(),listeners=new Map<Element,EventListener>(),moveListeners=new Map<Element,EventListener>();let currentConfig=config,stopped=false,device=deviceKind(),focused:string|null=null,currentState=new URLSearchParams(window.location.search).get("studioState")||String(root.getAttribute("data-jalwa-live-state")||"normal");
 const getNodes=()=>{const base=(currentConfig?.sections??[]).filter(n=>n.props?.roomType===kind&&(n.props?.roomState===currentState||!n.props?.roomState));const saved=getLiveRoomStateConfig(currentConfig??({sections:[]} as AppPageConfig),kind,currentState);return (saved?.sections??base).filter(n=>n.props?.roomType===kind&&(n.props?.roomState===currentState||!n.props?.roomState))};
 const setState=(state:string)=>{currentState=state||"normal";root.setAttribute("data-jalwa-live-state",currentState);bind()};
 const bind=()=>{if(stopped)return;device=deviceKind();const nodes=getNodes();const counters=new Map<string,number>();for(const node of nodes){const componentId=String(node.props?.componentId??""),component=registry.get(componentId),type=String(node.props?.componentType??component?.runtimeType??component?.type??"");if(!type)continue;const matches=findElements(type),index=Number(node.props?.instanceIndex??counters.get(componentId)??0);counters.set(componentId,index+1);const target=matches[index]??matches[0];if(!target)continue;const key=stableKey(node);applyNode(target,node,device);if(target instanceof HTMLElement){target.setAttribute("data-jalwa-live-stable-key",key);target.style.outline=focused===key?"2px solid hsl(var(--primary))":"";target.style.outlineOffset=focused===key?"2px":""}if(studioPreview&&bound.get(target)!==key&&target instanceof HTMLElement){const click:EventListener=e=>{e.preventDefault();e.stopPropagation();window.parent.postMessage({type:"jalwa-live-select",nodeId:node.id,componentId,instanceIndex:index,stableKey:key,roomType:kind,roomState:currentState},"*")};target.addEventListener("click",click,true);bound.set(target,key);listeners.set(target,click);const drag:EventListener=e=>{if(node.locked||(e instanceof PointerEvent&&e.button!==0))return;if(!(e instanceof PointerEvent))return;e.preventDefault();e.stopPropagation();window.parent.postMessage({type:"jalwa-live-select",nodeId:node.id,componentId,instanceIndex:index,stableKey:key,roomType:kind,roomState:currentState},"*");const sx=e.clientX,sy=e.clientY,[tx,ty]=[Number(node.responsive?.[device]?.style?.x??node.style?.x??0),Number(node.responsive?.[device]?.style?.y??node.style?.y??0)];target.setPointerCapture?.(e.pointerId);const move=(m:PointerEvent)=>{target.style.translate=`${tx+m.clientX-sx}px ${ty+m.clientY-sy}px`};const up=(u:PointerEvent)=>{target.releasePointerCapture?.(u.pointerId);target.removeEventListener("pointermove",move);target.removeEventListener("pointerup",up);window.parent.postMessage({type:"jalwa-live-move",nodeId:node.id,componentId,instanceIndex:index,stableKey:key,x:Math.round(tx+u.clientX-sx),y:Math.round(ty+u.clientY-sy),device,roomType:kind,roomState:currentState},"*")};target.addEventListener("pointermove",move);target.addEventListener("pointerup",up,{once:true})};target.addEventListener("pointerdown",drag,true);moveListeners.set(target,drag);target.style.cursor="move"}};
 const studioMessage=(e:MessageEvent)=>{if(!studioPreview)return;if(e.data?.type==="jalwa-live-studio-config"&&e.data.config){currentConfig=e.data.config as AppPageConfig;currentState=String(e.data.state??currentState);root.setAttribute("data-jalwa-live-state",currentState);bind()}if(e.data?.type==="jalwa-live-state"){setState(String(e.data.state??"normal"))}if(e.data?.type==="jalwa-live-focus"){focused=String(e.data.stableKey??e.data.componentId??"");if(e.data.state)currentState=String(e.data.state);bind();const matches=findElements(String(e.data.componentId??""));const index=Number(e.data.instanceIndex??0);matches[index]?.scrollIntoView?.({behavior:"smooth",block:"center",inline:"center"})}};
 const stateEvent=(e:Event)=>{const detail=(e as CustomEvent).detail as {state?:string}|undefined;if(detail?.state)setState(detail.state)};window.addEventListener("message",studioMessage);window.addEventListener("jalwa-live-room-state",stateEvent);const onResize=()=>bind();window.addEventListener("resize",onResize);bind();const observer=new MutationObserver(()=>bind());observer.observe(root,{childList:true,subtree:true});return()=>{stopped=true;observer.disconnect();window.removeEventListener("resize",onResize);window.removeEventListener("message",studioMessage);window.removeEventListener("jalwa-live-room-state",stateEvent);listeners.forEach((l,t)=>t.removeEventListener("click",l,true));moveListeners.forEach((l,t)=>t.removeEventListener("pointerdown",l,true));listeners.clear();moveListeners.clear()}}
