import type { AppComponentNode, AppPageConfig, ComponentStyle, DeviceKind } from "./schema";
import { studioSelector } from "./component-registry";

const CSS_PROPS: Record<string,string> = { width:"width",height:"height",minWidth:"min-width",maxWidth:"max-width",minHeight:"min-height",maxHeight:"max-height",top:"top",right:"right",bottom:"bottom",left:"left",position:"position",zIndex:"z-index",display:"display",flexDirection:"flex-direction",alignItems:"align-items",justifyContent:"justify-content",gridTemplateColumns:"grid-template-columns",overflow:"overflow",background:"background",backgroundImage:"background-image",color:"color",opacity:"opacity",filter:"filter",backdropFilter:"backdrop-filter",border:"border",borderWidth:"border-width",borderColor:"border-color",borderStyle:"border-style",borderRadius:"border-radius",borderTopLeftRadius:"border-top-left-radius",borderTopRightRadius:"border-top-right-radius",borderBottomRightRadius:"border-bottom-right-radius",borderBottomLeftRadius:"border-bottom-left-radius",boxShadow:"box-shadow",transform:"transform",translate:"translate",fontFamily:"font-family",fontSize:"font-size",fontWeight:"font-weight",fontStyle:"font-style",lineHeight:"line-height",letterSpacing:"letter-spacing",textAlign:"text-align",textTransform:"text-transform",textDecoration:"text-decoration",textShadow:"text-shadow",objectFit:"object-fit",objectPosition:"object-position",gap:"gap",rowGap:"row-gap",columnGap:"column-gap",padding:"padding",margin:"margin" };
const UNIT_LESS = new Set(["opacity","zIndex","fontWeight","lineHeight"]);
function cssValue(key:string,value:unknown):string|null { if(value===undefined||value===null||value==="")return null; if(typeof value==="number")return UNIT_LESS.has(key)?String(value):`${value}px`; return String(value); }
function applyStyle(el:HTMLElement,style?:ComponentStyle){ if(!style)return; for(const[key,value]of Object.entries(style)){const property=CSS_PROPS[key];if(!property)continue;const normalized=cssValue(key,value);if(normalized===null)el.style.removeProperty(property);else el.style.setProperty(property,normalized,"important");} if(style.spacing)for(const[side,value]of Object.entries(style.spacing))if(side!=="linked"&&value!==undefined)el.style.setProperty(`padding-${side}`,String(value),"important"); }
function findComponent(nodes:AppComponentNode[],id:string):AppComponentNode|undefined{for(const node of nodes){if(!node||typeof node!=="object")continue;if(node.id===id)return node;const found=Array.isArray(node.children)?findComponent(node.children,id):undefined;if(found)return found;}return undefined;}
function resolveTokens(style:ComponentStyle,config:AppPageConfig):ComponentStyle{const colors=config.tokens?.colors??{};const out={...style};for(const key of ["background","color","borderColor"] as const){const value=out[key];if(typeof value==="string"&&value.startsWith("token:"))out[key]=colors[value.slice(6)]??value;}return out;}
function applyContent(el:HTMLElement,node:AppComponentNode){const props=node.props??{};if(typeof props.text==="string"&&el.dataset.jalwaStudioText!=="preserve")el.textContent=props.text;if(typeof props.label==="string"&&el.dataset.jalwaStudioLabel!=="preserve"&&el.childElementCount===0)el.textContent=props.label;if(typeof props.src==="string"&&el instanceof HTMLImageElement)el.src=props.src;if(typeof props.alt==="string"&&el instanceof HTMLImageElement)el.alt=props.alt;}
function applyNode(node:AppComponentNode|undefined,device:DeviceKind,config:AppPageConfig){if(!node||typeof node!=="object"||typeof node.id!=="string")return;let elements:NodeListOf<Element>;try{elements=document.querySelectorAll(studioSelector(node.id));}catch{return;}elements.forEach(raw=>{if(!(raw instanceof HTMLElement))return;const el=raw;const rule=node.responsive?.[device];if(node.visible===false||rule?.visible===false)el.style.setProperty("display","none","important");else if(node.visible===true||rule?.visible===true)el.style.removeProperty("display");applyStyle(el,resolveTokens(node.style??{},config));applyStyle(el,resolveTokens(rule?.style??{},config));applyContent(el,node);el.dataset.jalwaStudioComponent=node.id;});if(Array.isArray(node.children))node.children.forEach(child=>applyNode(child,device,config));}
function applyOverrides(config:AppPageConfig){for(const override of config.runtimeOverrides??[]){if(!override||typeof override.selector!=="string")continue;let nodes:NodeListOf<Element>;try{nodes=document.querySelectorAll(override.selector);}catch{continue;}nodes.forEach(raw=>{if(!(raw instanceof HTMLElement))return;const el=raw;applyStyle(el,resolveTokens(override.style,config));if(override.visible===false)el.style.setProperty("display","none","important");else if(override.visible===true)el.style.removeProperty("display");});}}
function applyTokens(config:AppPageConfig){const root=document.documentElement;for(const[k,v]of Object.entries(config.tokens?.colors??{}))root.style.setProperty(`--jalwa-${k}`,v);for(const[k,v]of Object.entries(config.tokens?.spacing??{}))root.style.setProperty(`--jalwa-spacing-${k}`,String(v));for(const[k,v]of Object.entries(config.tokens?.radius??{}))root.style.setProperty(`--jalwa-radius-${k}`,String(v));for(const[k,v]of Object.entries(config.tokens?.shadows??{}))root.style.setProperty(`--jalwa-shadow-${k}`,v);}
function applyContentOverrides(config:AppPageConfig){for(const override of config.contentOverrides??[]){if(!override||typeof override.id!=="string")continue;let nodes:NodeListOf<Element>;try{nodes=document.querySelectorAll(studioSelector(override.id));}catch{continue;}nodes.forEach(raw=>{if(!(raw instanceof HTMLElement))return;const el=raw;if(override.key==="placeholder")el.setAttribute("placeholder",override.value);else if(["text","label","textContent"].includes(override.key))el.textContent=override.value;else if(override.key==="src")el.setAttribute("src",override.value);else if(override.key==="alt")el.setAttribute("alt",override.value);});}}
export function renderPublishedConfig(config:AppPageConfig,device:DeviceKind){if(!config||typeof config!=="object")return;applyTokens(config);(Array.isArray(config.sections)?config.sections:[]).forEach(node=>applyNode(node,device,config));applyOverrides(config);applyContentOverrides(config);}
export function createProductionRenderer(config:AppPageConfig){let frame=0;const render=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>renderPublishedConfig(config,window.innerWidth<768?"mobile":window.innerWidth<1024?"tablet":"desktop"));};render();const observer=new MutationObserver(render);observer.observe(document.body,{childList:true,subtree:true});window.addEventListener("resize",render);return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener("resize",render);};}
