/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RankRouteImport } from './routes/rank'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as GiftPreviewRouteImport } from './routes/gift-preview'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as MessagesPeerIdRouteImport } from './routes/messages_.$peerId'
import { Route as ApiZegoTokenRouteImport } from './routes/api/zego-token'
import { Route as ApiSendEmailRouteImport } from './routes/api/send-email'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVipRouteImport } from './routes/_authenticated/vip'
import { Route as AuthenticatedThemeShopRouteImport } from './routes/_authenticated/theme-shop'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRechargeHistoryRouteImport } from './routes/_authenticated/recharge-history'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedPkHistoryRouteImport } from './routes/_authenticated/pk-history'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyRoomsRouteImport } from './routes/_authenticated/my-rooms'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedCustomThemeRouteImport } from './routes/_authenticated/custom-theme'
import { Route as AuthenticatedCreateRoomRouteImport } from './routes/_authenticated/create-room'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGamesIndexRouteImport } from './routes/_authenticated/games.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicSmtpVerifyRouteImport } from './routes/api/public/smtp-verify'
import { Route as ApiPublicPushWebhookRouteImport } from './routes/api/public/push-webhook'
import { Route as ApiPublicFirebaseConfigRouteImport } from './routes/api/public/firebase-config'
import { Route as AuthenticatedUUserIdRouteImport } from './routes/_authenticated/u.$userId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedGamesLuckySpinRouteImport } from './routes/_authenticated/games.lucky-spin'
import { Route as AuthenticatedGamesDailySpinRouteImport } from './routes/_authenticated/games.daily-spin'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin.withdrawals'
import { Route as AuthenticatedAdminVipLevelsRouteImport } from './routes/_authenticated/admin.vip-levels'
import { Route as AuthenticatedAdminVipRouteImport } from './routes/_authenticated/admin.vip'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminThemesRouteImport } from './routes/_authenticated/admin.themes'
import { Route as AuthenticatedAdminThemeCategoriesRouteImport } from './routes/_authenticated/admin.theme-categories'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSplashRouteImport } from './routes/_authenticated/admin.splash'
import { Route as AuthenticatedAdminSpinPrizesRouteImport } from './routes/_authenticated/admin.spin-prizes'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRoomsRouteImport } from './routes/_authenticated/admin.rooms'
import { Route as AuthenticatedAdminRoomBackgroundsRouteImport } from './routes/_authenticated/admin.room-backgrounds'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminRechargeRouteImport } from './routes/_authenticated/admin.recharge'
import { Route as AuthenticatedAdminRankingsRouteImport } from './routes/_authenticated/admin.rankings'
import { Route as AuthenticatedAdminProfileAdminRouteImport } from './routes/_authenticated/admin.profile-admin'
import { Route as AuthenticatedAdminPkRouteImport } from './routes/_authenticated/admin.pk'
import { Route as AuthenticatedAdminPaymentAccountsRouteImport } from './routes/_authenticated/admin.payment-accounts'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin.live'
import { Route as AuthenticatedAdminIntegrationsRouteImport } from './routes/_authenticated/admin.integrations'
import { Route as AuthenticatedAdminGiftsRouteImport } from './routes/_authenticated/admin.gifts'
import { Route as AuthenticatedAdminFreeAccountsRouteImport } from './routes/_authenticated/admin.free-accounts'
import { Route as AuthenticatedAdminFinanceReportsRouteImport } from './routes/_authenticated/admin.finance-reports'
import { Route as AuthenticatedAdminCustomThemesRouteImport } from './routes/_authenticated/admin.custom-themes'
import { Route as AuthenticatedAdminCoinsRouteImport } from './routes/_authenticated/admin.coins'
import { Route as AuthenticatedAdminCmsRouteImport } from './routes/_authenticated/admin.cms'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin.banners'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin.ads'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftPreviewRoute = GiftPreviewRouteImport.update({
  id: '/gift-preview',
  path: '/gift-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesPeerIdRoute = MessagesPeerIdRouteImport.update({
  id: '/messages_/$peerId',
  path: '/messages/$peerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZegoTokenRoute = ApiZegoTokenRouteImport.update({
  id: '/api/zego-token',
  path: '/api/zego-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendEmailRoute = ApiSendEmailRouteImport.update({
  id: '/api/send-email',
  path: '/api/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVipRoute = AuthenticatedVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThemeShopRoute = AuthenticatedThemeShopRouteImport.update({
  id: '/theme-shop',
  path: '/theme-shop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeHistoryRoute =
  AuthenticatedRechargeHistoryRouteImport.update({
    id: '/recharge-history',
    path: '/recharge-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPkHistoryRoute = AuthenticatedPkHistoryRouteImport.update({
  id: '/pk-history',
  path: '/pk-history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyRoomsRoute = AuthenticatedMyRoomsRouteImport.update({
  id: '/my-rooms',
  path: '/my-rooms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomThemeRoute =
  AuthenticatedCustomThemeRouteImport.update({
    id: '/custom-theme',
    path: '/custom-theme',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreateRoomRoute = AuthenticatedCreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesIndexRoute = AuthenticatedGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGamesRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicSmtpVerifyRoute = ApiPublicSmtpVerifyRouteImport.update({
  id: '/api/public/smtp-verify',
  path: '/api/public/smtp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushWebhookRoute = ApiPublicPushWebhookRouteImport.update({
  id: '/api/public/push-webhook',
  path: '/api/public/push-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFirebaseConfigRoute = ApiPublicFirebaseConfigRouteImport.update({
  id: '/api/public/firebase-config',
  path: '/api/public/firebase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUUserIdRoute = AuthenticatedUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedGamesLuckySpinRoute =
  AuthenticatedGamesLuckySpinRouteImport.update({
    id: '/lucky-spin',
    path: '/lucky-spin',
    getParentRoute: () => AuthenticatedGamesRoute,
  } as any)
const AuthenticatedGamesDailySpinRoute =
  AuthenticatedGamesDailySpinRouteImport.update({
    id: '/daily-spin',
    path: '/daily-spin',
    getParentRoute: () => AuthenticatedGamesRoute,
  } as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVipLevelsRoute =
  AuthenticatedAdminVipLevelsRouteImport.update({
    id: '/vip-levels',
    path: '/vip-levels',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVipRoute = AuthenticatedAdminVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminThemesRoute =
  AuthenticatedAdminThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminThemeCategoriesRoute =
  AuthenticatedAdminThemeCategoriesRouteImport.update({
    id: '/theme-categories',
    path: '/theme-categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSplashRoute =
  AuthenticatedAdminSplashRouteImport.update({
    id: '/splash',
    path: '/splash',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSpinPrizesRoute =
  AuthenticatedAdminSpinPrizesRouteImport.update({
    id: '/spin-prizes',
    path: '/spin-prizes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoomsRoute = AuthenticatedAdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRoomBackgroundsRoute =
  AuthenticatedAdminRoomBackgroundsRouteImport.update({
    id: '/room-backgrounds',
    path: '/room-backgrounds',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRechargeRoute =
  AuthenticatedAdminRechargeRouteImport.update({
    id: '/recharge',
    path: '/recharge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRankingsRoute =
  AuthenticatedAdminRankingsRouteImport.update({
    id: '/rankings',
    path: '/rankings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileAdminRoute =
  AuthenticatedAdminProfileAdminRouteImport.update({
    id: '/profile-admin',
    path: '/profile-admin',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPkRoute = AuthenticatedAdminPkRouteImport.update({
  id: '/pk',
  path: '/pk',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentAccountsRoute =
  AuthenticatedAdminPaymentAccountsRouteImport.update({
    id: '/payment-accounts',
    path: '/payment-accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIntegrationsRoute =
  AuthenticatedAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGiftsRoute = AuthenticatedAdminGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFreeAccountsRoute =
  AuthenticatedAdminFreeAccountsRouteImport.update({
    id: '/free-accounts',
    path: '/free-accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceReportsRoute =
  AuthenticatedAdminFinanceReportsRouteImport.update({
    id: '/finance-reports',
    path: '/finance-reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomThemesRoute =
  AuthenticatedAdminCustomThemesRouteImport.update({
    id: '/custom-themes',
    path: '/custom-themes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoinsRoute = AuthenticatedAdminCoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCmsRoute = AuthenticatedAdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gift-preview': typeof GiftPreviewRoute
  '/messages': typeof MessagesRoute
  '/rank': typeof RankRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/splash': typeof SplashRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blocked': typeof AuthenticatedBlockedRoute
  '/create-room': typeof AuthenticatedCreateRoomRoute
  '/custom-theme': typeof AuthenticatedCustomThemeRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/games': typeof AuthenticatedGamesRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/my-rooms': typeof AuthenticatedMyRoomsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/pk-history': typeof AuthenticatedPkHistoryRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/recharge-history': typeof AuthenticatedRechargeHistoryRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/theme-shop': typeof AuthenticatedThemeShopRoute
  '/vip': typeof AuthenticatedVipRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/zego-token': typeof ApiZegoTokenRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/coins': typeof AuthenticatedAdminCoinsRoute
  '/admin/custom-themes': typeof AuthenticatedAdminCustomThemesRoute
  '/admin/finance-reports': typeof AuthenticatedAdminFinanceReportsRoute
  '/admin/free-accounts': typeof AuthenticatedAdminFreeAccountsRoute
  '/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/admin/pk': typeof AuthenticatedAdminPkRoute
  '/admin/profile-admin': typeof AuthenticatedAdminProfileAdminRoute
  '/admin/rankings': typeof AuthenticatedAdminRankingsRoute
  '/admin/recharge': typeof AuthenticatedAdminRechargeRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/room-backgrounds': typeof AuthenticatedAdminRoomBackgroundsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/spin-prizes': typeof AuthenticatedAdminSpinPrizesRoute
  '/admin/splash': typeof AuthenticatedAdminSplashRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/theme-categories': typeof AuthenticatedAdminThemeCategoriesRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vip': typeof AuthenticatedAdminVipRoute
  '/admin/vip-levels': typeof AuthenticatedAdminVipLevelsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/games/daily-spin': typeof AuthenticatedGamesDailySpinRoute
  '/games/lucky-spin': typeof AuthenticatedGamesLuckySpinRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/u/$userId': typeof AuthenticatedUUserIdRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/push-webhook': typeof ApiPublicPushWebhookRoute
  '/api/public/smtp-verify': typeof ApiPublicSmtpVerifyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/games/': typeof AuthenticatedGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/gift-preview': typeof GiftPreviewRoute
  '/messages': typeof MessagesRoute
  '/rank': typeof RankRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/splash': typeof SplashRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/create-room': typeof AuthenticatedCreateRoomRoute
  '/custom-theme': typeof AuthenticatedCustomThemeRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/me': typeof AuthenticatedMeRoute
  '/my-rooms': typeof AuthenticatedMyRoomsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/pk-history': typeof AuthenticatedPkHistoryRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/recharge-history': typeof AuthenticatedRechargeHistoryRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/theme-shop': typeof AuthenticatedThemeShopRoute
  '/vip': typeof AuthenticatedVipRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/zego-token': typeof ApiZegoTokenRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/admin/coins': typeof AuthenticatedAdminCoinsRoute
  '/admin/custom-themes': typeof AuthenticatedAdminCustomThemesRoute
  '/admin/finance-reports': typeof AuthenticatedAdminFinanceReportsRoute
  '/admin/free-accounts': typeof AuthenticatedAdminFreeAccountsRoute
  '/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/admin/pk': typeof AuthenticatedAdminPkRoute
  '/admin/profile-admin': typeof AuthenticatedAdminProfileAdminRoute
  '/admin/rankings': typeof AuthenticatedAdminRankingsRoute
  '/admin/recharge': typeof AuthenticatedAdminRechargeRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/room-backgrounds': typeof AuthenticatedAdminRoomBackgroundsRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/spin-prizes': typeof AuthenticatedAdminSpinPrizesRoute
  '/admin/splash': typeof AuthenticatedAdminSplashRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/theme-categories': typeof AuthenticatedAdminThemeCategoriesRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vip': typeof AuthenticatedAdminVipRoute
  '/admin/vip-levels': typeof AuthenticatedAdminVipLevelsRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/games/daily-spin': typeof AuthenticatedGamesDailySpinRoute
  '/games/lucky-spin': typeof AuthenticatedGamesLuckySpinRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/u/$userId': typeof AuthenticatedUUserIdRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/push-webhook': typeof ApiPublicPushWebhookRoute
  '/api/public/smtp-verify': typeof ApiPublicSmtpVerifyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/games': typeof AuthenticatedGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/gift-preview': typeof GiftPreviewRoute
  '/messages': typeof MessagesRoute
  '/rank': typeof RankRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/splash': typeof SplashRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_authenticated/create-room': typeof AuthenticatedCreateRoomRoute
  '/_authenticated/custom-theme': typeof AuthenticatedCustomThemeRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/games': typeof AuthenticatedGamesRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/my-rooms': typeof AuthenticatedMyRoomsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/_authenticated/pk-history': typeof AuthenticatedPkHistoryRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/recharge-history': typeof AuthenticatedRechargeHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/theme-shop': typeof AuthenticatedThemeShopRoute
  '/_authenticated/vip': typeof AuthenticatedVipRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/api/send-email': typeof ApiSendEmailRoute
  '/api/zego-token': typeof ApiZegoTokenRoute
  '/messages_/$peerId': typeof MessagesPeerIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/cms': typeof AuthenticatedAdminCmsRoute
  '/_authenticated/admin/coins': typeof AuthenticatedAdminCoinsRoute
  '/_authenticated/admin/custom-themes': typeof AuthenticatedAdminCustomThemesRoute
  '/_authenticated/admin/finance-reports': typeof AuthenticatedAdminFinanceReportsRoute
  '/_authenticated/admin/free-accounts': typeof AuthenticatedAdminFreeAccountsRoute
  '/_authenticated/admin/gifts': typeof AuthenticatedAdminGiftsRoute
  '/_authenticated/admin/integrations': typeof AuthenticatedAdminIntegrationsRoute
  '/_authenticated/admin/live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/_authenticated/admin/pk': typeof AuthenticatedAdminPkRoute
  '/_authenticated/admin/profile-admin': typeof AuthenticatedAdminProfileAdminRoute
  '/_authenticated/admin/rankings': typeof AuthenticatedAdminRankingsRoute
  '/_authenticated/admin/recharge': typeof AuthenticatedAdminRechargeRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/room-backgrounds': typeof AuthenticatedAdminRoomBackgroundsRoute
  '/_authenticated/admin/rooms': typeof AuthenticatedAdminRoomsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/spin-prizes': typeof AuthenticatedAdminSpinPrizesRoute
  '/_authenticated/admin/splash': typeof AuthenticatedAdminSplashRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/theme-categories': typeof AuthenticatedAdminThemeCategoriesRoute
  '/_authenticated/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vip': typeof AuthenticatedAdminVipRoute
  '/_authenticated/admin/vip-levels': typeof AuthenticatedAdminVipLevelsRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/games/daily-spin': typeof AuthenticatedGamesDailySpinRoute
  '/_authenticated/games/lucky-spin': typeof AuthenticatedGamesLuckySpinRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/u/$userId': typeof AuthenticatedUUserIdRoute
  '/api/public/firebase-config': typeof ApiPublicFirebaseConfigRoute
  '/api/public/push-webhook': typeof ApiPublicPushWebhookRoute
  '/api/public/smtp-verify': typeof ApiPublicSmtpVerifyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/games/': typeof AuthenticatedGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/gift-preview'
    | '/messages'
    | '/rank'
    | '/reset-password'
    | '/rooms'
    | '/splash'
    | '/admin'
    | '/blocked'
    | '/create-room'
    | '/custom-theme'
    | '/friends'
    | '/gallery'
    | '/games'
    | '/me'
    | '/my-rooms'
    | '/notifications'
    | '/partner'
    | '/pk-history'
    | '/privacy'
    | '/recharge'
    | '/recharge-history'
    | '/settings'
    | '/theme-shop'
    | '/vip'
    | '/wallet'
    | '/withdraw'
    | '/api/send-email'
    | '/api/zego-token'
    | '/messages/$peerId'
    | '/room/$roomId'
    | '/admin/ads'
    | '/admin/banners'
    | '/admin/cms'
    | '/admin/coins'
    | '/admin/custom-themes'
    | '/admin/finance-reports'
    | '/admin/free-accounts'
    | '/admin/gifts'
    | '/admin/integrations'
    | '/admin/live'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/payment-accounts'
    | '/admin/pk'
    | '/admin/profile-admin'
    | '/admin/rankings'
    | '/admin/recharge'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/room-backgrounds'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/spin-prizes'
    | '/admin/splash'
    | '/admin/support'
    | '/admin/theme-categories'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/vip'
    | '/admin/vip-levels'
    | '/admin/withdrawals'
    | '/games/daily-spin'
    | '/games/lucky-spin'
    | '/settings/notifications'
    | '/u/$userId'
    | '/api/public/firebase-config'
    | '/api/public/push-webhook'
    | '/api/public/smtp-verify'
    | '/admin/'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/gift-preview'
    | '/messages'
    | '/rank'
    | '/reset-password'
    | '/rooms'
    | '/splash'
    | '/blocked'
    | '/create-room'
    | '/custom-theme'
    | '/friends'
    | '/gallery'
    | '/me'
    | '/my-rooms'
    | '/notifications'
    | '/partner'
    | '/pk-history'
    | '/privacy'
    | '/recharge'
    | '/recharge-history'
    | '/settings'
    | '/theme-shop'
    | '/vip'
    | '/wallet'
    | '/withdraw'
    | '/api/send-email'
    | '/api/zego-token'
    | '/messages/$peerId'
    | '/room/$roomId'
    | '/admin/ads'
    | '/admin/banners'
    | '/admin/cms'
    | '/admin/coins'
    | '/admin/custom-themes'
    | '/admin/finance-reports'
    | '/admin/free-accounts'
    | '/admin/gifts'
    | '/admin/integrations'
    | '/admin/live'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/payment-accounts'
    | '/admin/pk'
    | '/admin/profile-admin'
    | '/admin/rankings'
    | '/admin/recharge'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/room-backgrounds'
    | '/admin/rooms'
    | '/admin/settings'
    | '/admin/spin-prizes'
    | '/admin/splash'
    | '/admin/support'
    | '/admin/theme-categories'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/vip'
    | '/admin/vip-levels'
    | '/admin/withdrawals'
    | '/games/daily-spin'
    | '/games/lucky-spin'
    | '/settings/notifications'
    | '/u/$userId'
    | '/api/public/firebase-config'
    | '/api/public/push-webhook'
    | '/api/public/smtp-verify'
    | '/admin'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/gift-preview'
    | '/messages'
    | '/rank'
    | '/reset-password'
    | '/rooms'
    | '/splash'
    | '/_authenticated/admin'
    | '/_authenticated/blocked'
    | '/_authenticated/create-room'
    | '/_authenticated/custom-theme'
    | '/_authenticated/friends'
    | '/_authenticated/gallery'
    | '/_authenticated/games'
    | '/_authenticated/me'
    | '/_authenticated/my-rooms'
    | '/_authenticated/notifications'
    | '/_authenticated/partner'
    | '/_authenticated/pk-history'
    | '/_authenticated/privacy'
    | '/_authenticated/recharge'
    | '/_authenticated/recharge-history'
    | '/_authenticated/settings'
    | '/_authenticated/theme-shop'
    | '/_authenticated/vip'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/api/send-email'
    | '/api/zego-token'
    | '/messages_/$peerId'
    | '/room/$roomId'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/cms'
    | '/_authenticated/admin/coins'
    | '/_authenticated/admin/custom-themes'
    | '/_authenticated/admin/finance-reports'
    | '/_authenticated/admin/free-accounts'
    | '/_authenticated/admin/gifts'
    | '/_authenticated/admin/integrations'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/payment-accounts'
    | '/_authenticated/admin/pk'
    | '/_authenticated/admin/profile-admin'
    | '/_authenticated/admin/rankings'
    | '/_authenticated/admin/recharge'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/room-backgrounds'
    | '/_authenticated/admin/rooms'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/spin-prizes'
    | '/_authenticated/admin/splash'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/theme-categories'
    | '/_authenticated/admin/themes'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vip'
    | '/_authenticated/admin/vip-levels'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/games/daily-spin'
    | '/_authenticated/games/lucky-spin'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/u/$userId'
    | '/api/public/firebase-config'
    | '/api/public/push-webhook'
    | '/api/public/smtp-verify'
    | '/_authenticated/admin/'
    | '/_authenticated/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GiftPreviewRoute: typeof GiftPreviewRoute
  MessagesRoute: typeof MessagesRoute
  RankRoute: typeof RankRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoute: typeof RoomsRoute
  SplashRoute: typeof SplashRoute
  ApiSendEmailRoute: typeof ApiSendEmailRoute
  ApiZegoTokenRoute: typeof ApiZegoTokenRoute
  MessagesPeerIdRoute: typeof MessagesPeerIdRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  ApiPublicFirebaseConfigRoute: typeof ApiPublicFirebaseConfigRoute
  ApiPublicPushWebhookRoute: typeof ApiPublicPushWebhookRoute
  ApiPublicSmtpVerifyRoute: typeof ApiPublicSmtpVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-preview': {
      id: '/gift-preview'
      path: '/gift-preview'
      fullPath: '/gift-preview'
      preLoaderRoute: typeof GiftPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages_/$peerId': {
      id: '/messages_/$peerId'
      path: '/messages/$peerId'
      fullPath: '/messages/$peerId'
      preLoaderRoute: typeof MessagesPeerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zego-token': {
      id: '/api/zego-token'
      path: '/api/zego-token'
      fullPath: '/api/zego-token'
      preLoaderRoute: typeof ApiZegoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-email': {
      id: '/api/send-email'
      path: '/api/send-email'
      fullPath: '/api/send-email'
      preLoaderRoute: typeof ApiSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vip': {
      id: '/_authenticated/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof AuthenticatedVipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/theme-shop': {
      id: '/_authenticated/theme-shop'
      path: '/theme-shop'
      fullPath: '/theme-shop'
      preLoaderRoute: typeof AuthenticatedThemeShopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge-history': {
      id: '/_authenticated/recharge-history'
      path: '/recharge-history'
      fullPath: '/recharge-history'
      preLoaderRoute: typeof AuthenticatedRechargeHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pk-history': {
      id: '/_authenticated/pk-history'
      path: '/pk-history'
      fullPath: '/pk-history'
      preLoaderRoute: typeof AuthenticatedPkHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-rooms': {
      id: '/_authenticated/my-rooms'
      path: '/my-rooms'
      fullPath: '/my-rooms'
      preLoaderRoute: typeof AuthenticatedMyRoomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custom-theme': {
      id: '/_authenticated/custom-theme'
      path: '/custom-theme'
      fullPath: '/custom-theme'
      preLoaderRoute: typeof AuthenticatedCustomThemeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-room': {
      id: '/_authenticated/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof AuthenticatedCreateRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games/': {
      id: '/_authenticated/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof AuthenticatedGamesIndexRouteImport
      parentRoute: typeof AuthenticatedGamesRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/smtp-verify': {
      id: '/api/public/smtp-verify'
      path: '/api/public/smtp-verify'
      fullPath: '/api/public/smtp-verify'
      preLoaderRoute: typeof ApiPublicSmtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-webhook': {
      id: '/api/public/push-webhook'
      path: '/api/public/push-webhook'
      fullPath: '/api/public/push-webhook'
      preLoaderRoute: typeof ApiPublicPushWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firebase-config': {
      id: '/api/public/firebase-config'
      path: '/api/public/firebase-config'
      fullPath: '/api/public/firebase-config'
      preLoaderRoute: typeof ApiPublicFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/u/$userId': {
      id: '/_authenticated/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AuthenticatedUUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/games/lucky-spin': {
      id: '/_authenticated/games/lucky-spin'
      path: '/lucky-spin'
      fullPath: '/games/lucky-spin'
      preLoaderRoute: typeof AuthenticatedGamesLuckySpinRouteImport
      parentRoute: typeof AuthenticatedGamesRoute
    }
    '/_authenticated/games/daily-spin': {
      id: '/_authenticated/games/daily-spin'
      path: '/daily-spin'
      fullPath: '/games/daily-spin'
      preLoaderRoute: typeof AuthenticatedGamesDailySpinRouteImport
      parentRoute: typeof AuthenticatedGamesRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vip-levels': {
      id: '/_authenticated/admin/vip-levels'
      path: '/vip-levels'
      fullPath: '/admin/vip-levels'
      preLoaderRoute: typeof AuthenticatedAdminVipLevelsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vip': {
      id: '/_authenticated/admin/vip'
      path: '/vip'
      fullPath: '/admin/vip'
      preLoaderRoute: typeof AuthenticatedAdminVipRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/themes': {
      id: '/_authenticated/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AuthenticatedAdminThemesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/theme-categories': {
      id: '/_authenticated/admin/theme-categories'
      path: '/theme-categories'
      fullPath: '/admin/theme-categories'
      preLoaderRoute: typeof AuthenticatedAdminThemeCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/splash': {
      id: '/_authenticated/admin/splash'
      path: '/splash'
      fullPath: '/admin/splash'
      preLoaderRoute: typeof AuthenticatedAdminSplashRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/spin-prizes': {
      id: '/_authenticated/admin/spin-prizes'
      path: '/spin-prizes'
      fullPath: '/admin/spin-prizes'
      preLoaderRoute: typeof AuthenticatedAdminSpinPrizesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rooms': {
      id: '/_authenticated/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/room-backgrounds': {
      id: '/_authenticated/admin/room-backgrounds'
      path: '/room-backgrounds'
      fullPath: '/admin/room-backgrounds'
      preLoaderRoute: typeof AuthenticatedAdminRoomBackgroundsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recharge': {
      id: '/_authenticated/admin/recharge'
      path: '/recharge'
      fullPath: '/admin/recharge'
      preLoaderRoute: typeof AuthenticatedAdminRechargeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rankings': {
      id: '/_authenticated/admin/rankings'
      path: '/rankings'
      fullPath: '/admin/rankings'
      preLoaderRoute: typeof AuthenticatedAdminRankingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile-admin': {
      id: '/_authenticated/admin/profile-admin'
      path: '/profile-admin'
      fullPath: '/admin/profile-admin'
      preLoaderRoute: typeof AuthenticatedAdminProfileAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pk': {
      id: '/_authenticated/admin/pk'
      path: '/pk'
      fullPath: '/admin/pk'
      preLoaderRoute: typeof AuthenticatedAdminPkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payment-accounts': {
      id: '/_authenticated/admin/payment-accounts'
      path: '/payment-accounts'
      fullPath: '/admin/payment-accounts'
      preLoaderRoute: typeof AuthenticatedAdminPaymentAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/live': {
      id: '/_authenticated/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/integrations': {
      id: '/_authenticated/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AuthenticatedAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gifts': {
      id: '/_authenticated/admin/gifts'
      path: '/gifts'
      fullPath: '/admin/gifts'
      preLoaderRoute: typeof AuthenticatedAdminGiftsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/free-accounts': {
      id: '/_authenticated/admin/free-accounts'
      path: '/free-accounts'
      fullPath: '/admin/free-accounts'
      preLoaderRoute: typeof AuthenticatedAdminFreeAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance-reports': {
      id: '/_authenticated/admin/finance-reports'
      path: '/finance-reports'
      fullPath: '/admin/finance-reports'
      preLoaderRoute: typeof AuthenticatedAdminFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/custom-themes': {
      id: '/_authenticated/admin/custom-themes'
      path: '/custom-themes'
      fullPath: '/admin/custom-themes'
      preLoaderRoute: typeof AuthenticatedAdminCustomThemesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coins': {
      id: '/_authenticated/admin/coins'
      path: '/coins'
      fullPath: '/admin/coins'
      preLoaderRoute: typeof AuthenticatedAdminCoinsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms': {
      id: '/_authenticated/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AuthenticatedAdminCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminCmsRoute: typeof AuthenticatedAdminCmsRoute
  AuthenticatedAdminCoinsRoute: typeof AuthenticatedAdminCoinsRoute
  AuthenticatedAdminCustomThemesRoute: typeof AuthenticatedAdminCustomThemesRoute
  AuthenticatedAdminFinanceReportsRoute: typeof AuthenticatedAdminFinanceReportsRoute
  AuthenticatedAdminFreeAccountsRoute: typeof AuthenticatedAdminFreeAccountsRoute
  AuthenticatedAdminGiftsRoute: typeof AuthenticatedAdminGiftsRoute
  AuthenticatedAdminIntegrationsRoute: typeof AuthenticatedAdminIntegrationsRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminPaymentAccountsRoute: typeof AuthenticatedAdminPaymentAccountsRoute
  AuthenticatedAdminPkRoute: typeof AuthenticatedAdminPkRoute
  AuthenticatedAdminProfileAdminRoute: typeof AuthenticatedAdminProfileAdminRoute
  AuthenticatedAdminRankingsRoute: typeof AuthenticatedAdminRankingsRoute
  AuthenticatedAdminRechargeRoute: typeof AuthenticatedAdminRechargeRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminRoomBackgroundsRoute: typeof AuthenticatedAdminRoomBackgroundsRoute
  AuthenticatedAdminRoomsRoute: typeof AuthenticatedAdminRoomsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSpinPrizesRoute: typeof AuthenticatedAdminSpinPrizesRoute
  AuthenticatedAdminSplashRoute: typeof AuthenticatedAdminSplashRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminThemeCategoriesRoute: typeof AuthenticatedAdminThemeCategoriesRoute
  AuthenticatedAdminThemesRoute: typeof AuthenticatedAdminThemesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVipRoute: typeof AuthenticatedAdminVipRoute
  AuthenticatedAdminVipLevelsRoute: typeof AuthenticatedAdminVipLevelsRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedAdminCmsRoute: AuthenticatedAdminCmsRoute,
  AuthenticatedAdminCoinsRoute: AuthenticatedAdminCoinsRoute,
  AuthenticatedAdminCustomThemesRoute: AuthenticatedAdminCustomThemesRoute,
  AuthenticatedAdminFinanceReportsRoute: AuthenticatedAdminFinanceReportsRoute,
  AuthenticatedAdminFreeAccountsRoute: AuthenticatedAdminFreeAccountsRoute,
  AuthenticatedAdminGiftsRoute: AuthenticatedAdminGiftsRoute,
  AuthenticatedAdminIntegrationsRoute: AuthenticatedAdminIntegrationsRoute,
  AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminPaymentAccountsRoute:
    AuthenticatedAdminPaymentAccountsRoute,
  AuthenticatedAdminPkRoute: AuthenticatedAdminPkRoute,
  AuthenticatedAdminProfileAdminRoute: AuthenticatedAdminProfileAdminRoute,
  AuthenticatedAdminRankingsRoute: AuthenticatedAdminRankingsRoute,
  AuthenticatedAdminRechargeRoute: AuthenticatedAdminRechargeRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminRoomBackgroundsRoute:
    AuthenticatedAdminRoomBackgroundsRoute,
  AuthenticatedAdminRoomsRoute: AuthenticatedAdminRoomsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSpinPrizesRoute: AuthenticatedAdminSpinPrizesRoute,
  AuthenticatedAdminSplashRoute: AuthenticatedAdminSplashRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminThemeCategoriesRoute:
    AuthenticatedAdminThemeCategoriesRoute,
  AuthenticatedAdminThemesRoute: AuthenticatedAdminThemesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVipRoute: AuthenticatedAdminVipRoute,
  AuthenticatedAdminVipLevelsRoute: AuthenticatedAdminVipLevelsRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGamesRouteChildren {
  AuthenticatedGamesDailySpinRoute: typeof AuthenticatedGamesDailySpinRoute
  AuthenticatedGamesLuckySpinRoute: typeof AuthenticatedGamesLuckySpinRoute
  AuthenticatedGamesIndexRoute: typeof AuthenticatedGamesIndexRoute
}

const AuthenticatedGamesRouteChildren: AuthenticatedGamesRouteChildren = {
  AuthenticatedGamesDailySpinRoute: AuthenticatedGamesDailySpinRoute,
  AuthenticatedGamesLuckySpinRoute: AuthenticatedGamesLuckySpinRoute,
  AuthenticatedGamesIndexRoute: AuthenticatedGamesIndexRoute,
}

const AuthenticatedGamesRouteWithChildren =
  AuthenticatedGamesRoute._addFileChildren(AuthenticatedGamesRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
  AuthenticatedCreateRoomRoute: typeof AuthenticatedCreateRoomRoute
  AuthenticatedCustomThemeRoute: typeof AuthenticatedCustomThemeRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMyRoomsRoute: typeof AuthenticatedMyRoomsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedPkHistoryRoute: typeof AuthenticatedPkHistoryRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedRechargeHistoryRoute: typeof AuthenticatedRechargeHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedThemeShopRoute: typeof AuthenticatedThemeShopRoute
  AuthenticatedVipRoute: typeof AuthenticatedVipRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedUUserIdRoute: typeof AuthenticatedUUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
  AuthenticatedCreateRoomRoute: AuthenticatedCreateRoomRoute,
  AuthenticatedCustomThemeRoute: AuthenticatedCustomThemeRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMyRoomsRoute: AuthenticatedMyRoomsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedPkHistoryRoute: AuthenticatedPkHistoryRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedRechargeHistoryRoute: AuthenticatedRechargeHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedThemeShopRoute: AuthenticatedThemeShopRoute,
  AuthenticatedVipRoute: AuthenticatedVipRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedUUserIdRoute: AuthenticatedUUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GiftPreviewRoute: GiftPreviewRoute,
  MessagesRoute: MessagesRoute,
  RankRoute: RankRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoute: RoomsRoute,
  SplashRoute: SplashRoute,
  ApiSendEmailRoute: ApiSendEmailRoute,
  ApiZegoTokenRoute: ApiZegoTokenRoute,
  MessagesPeerIdRoute: MessagesPeerIdRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  ApiPublicFirebaseConfigRoute: ApiPublicFirebaseConfigRoute,
  ApiPublicPushWebhookRoute: ApiPublicPushWebhookRoute,
  ApiPublicSmtpVerifyRoute: ApiPublicSmtpVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
