/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as MessagesPeerIdRouteImport } from './routes/messages.$peerId'
import { Route as ApiAgoraTokenRouteImport } from './routes/api/agora-token'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedCreateRoomRouteImport } from './routes/_authenticated/create-room'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedGamesLuckySpinRouteImport } from './routes/_authenticated/games.lucky-spin'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminRechargeRouteImport } from './routes/_authenticated/admin.recharge'
import { Route as AuthenticatedAdminPaymentAccountsRouteImport } from './routes/_authenticated/admin.payment-accounts'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesPeerIdRoute = MessagesPeerIdRouteImport.update({
  id: '/$peerId',
  path: '/$peerId',
  getParentRoute: () => MessagesRoute,
} as any)
const ApiAgoraTokenRoute = ApiAgoraTokenRouteImport.update({
  id: '/api/agora-token',
  path: '/api/agora-token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoomRoute = AuthenticatedCreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedGamesLuckySpinRoute =
  AuthenticatedGamesLuckySpinRouteImport.update({
    id: '/lucky-spin',
    path: '/lucky-spin',
    getParentRoute: () => AuthenticatedGamesRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRechargeRoute =
  AuthenticatedAdminRechargeRouteImport.update({
    id: '/recharge',
    path: '/recharge',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentAccountsRoute =
  AuthenticatedAdminPaymentAccountsRouteImport.update({
    id: '/payment-accounts',
    path: '/payment-accounts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/splash': typeof SplashRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/create-room': typeof AuthenticatedCreateRoomRoute
  '/games': typeof AuthenticatedGamesRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/agora-token': typeof ApiAgoraTokenRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/admin/recharge': typeof AuthenticatedAdminRechargeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/games/lucky-spin': typeof AuthenticatedGamesLuckySpinRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/splash': typeof SplashRoute
  '/create-room': typeof AuthenticatedCreateRoomRoute
  '/games': typeof AuthenticatedGamesRouteWithChildren
  '/me': typeof AuthenticatedMeRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/agora-token': typeof ApiAgoraTokenRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/admin/recharge': typeof AuthenticatedAdminRechargeRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/games/lucky-spin': typeof AuthenticatedGamesLuckySpinRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/splash': typeof SplashRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/create-room': typeof AuthenticatedCreateRoomRoute
  '/_authenticated/games': typeof AuthenticatedGamesRouteWithChildren
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/agora-token': typeof ApiAgoraTokenRoute
  '/messages/$peerId': typeof MessagesPeerIdRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/_authenticated/admin/payment-accounts': typeof AuthenticatedAdminPaymentAccountsRoute
  '/_authenticated/admin/recharge': typeof AuthenticatedAdminRechargeRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/games/lucky-spin': typeof AuthenticatedGamesLuckySpinRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/messages'
    | '/reset-password'
    | '/rooms'
    | '/splash'
    | '/admin'
    | '/create-room'
    | '/games'
    | '/me'
    | '/recharge'
    | '/wallet'
    | '/api/agora-token'
    | '/messages/$peerId'
    | '/room/$roomId'
    | '/admin/payment-accounts'
    | '/admin/recharge'
    | '/admin/users'
    | '/games/lucky-spin'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/messages'
    | '/reset-password'
    | '/rooms'
    | '/splash'
    | '/create-room'
    | '/games'
    | '/me'
    | '/recharge'
    | '/wallet'
    | '/api/agora-token'
    | '/messages/$peerId'
    | '/room/$roomId'
    | '/admin/payment-accounts'
    | '/admin/recharge'
    | '/admin/users'
    | '/games/lucky-spin'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/messages'
    | '/reset-password'
    | '/rooms'
    | '/splash'
    | '/_authenticated/admin'
    | '/_authenticated/create-room'
    | '/_authenticated/games'
    | '/_authenticated/me'
    | '/_authenticated/recharge'
    | '/_authenticated/wallet'
    | '/api/agora-token'
    | '/messages/$peerId'
    | '/room/$roomId'
    | '/_authenticated/admin/payment-accounts'
    | '/_authenticated/admin/recharge'
    | '/_authenticated/admin/users'
    | '/_authenticated/games/lucky-spin'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoute: typeof RoomsRoute
  SplashRoute: typeof SplashRoute
  ApiAgoraTokenRoute: typeof ApiAgoraTokenRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$peerId': {
      id: '/messages/$peerId'
      path: '/$peerId'
      fullPath: '/messages/$peerId'
      preLoaderRoute: typeof MessagesPeerIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/api/agora-token': {
      id: '/api/agora-token'
      path: '/api/agora-token'
      fullPath: '/api/agora-token'
      preLoaderRoute: typeof ApiAgoraTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-room': {
      id: '/_authenticated/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof AuthenticatedCreateRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/games/lucky-spin': {
      id: '/_authenticated/games/lucky-spin'
      path: '/lucky-spin'
      fullPath: '/games/lucky-spin'
      preLoaderRoute: typeof AuthenticatedGamesLuckySpinRouteImport
      parentRoute: typeof AuthenticatedGamesRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/recharge': {
      id: '/_authenticated/admin/recharge'
      path: '/recharge'
      fullPath: '/admin/recharge'
      preLoaderRoute: typeof AuthenticatedAdminRechargeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payment-accounts': {
      id: '/_authenticated/admin/payment-accounts'
      path: '/payment-accounts'
      fullPath: '/admin/payment-accounts'
      preLoaderRoute: typeof AuthenticatedAdminPaymentAccountsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPaymentAccountsRoute: typeof AuthenticatedAdminPaymentAccountsRoute
  AuthenticatedAdminRechargeRoute: typeof AuthenticatedAdminRechargeRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPaymentAccountsRoute:
    AuthenticatedAdminPaymentAccountsRoute,
  AuthenticatedAdminRechargeRoute: AuthenticatedAdminRechargeRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedGamesRouteChildren {
  AuthenticatedGamesLuckySpinRoute: typeof AuthenticatedGamesLuckySpinRoute
}

const AuthenticatedGamesRouteChildren: AuthenticatedGamesRouteChildren = {
  AuthenticatedGamesLuckySpinRoute: AuthenticatedGamesLuckySpinRoute,
}

const AuthenticatedGamesRouteWithChildren =
  AuthenticatedGamesRoute._addFileChildren(AuthenticatedGamesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCreateRoomRoute: typeof AuthenticatedCreateRoomRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRouteWithChildren
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCreateRoomRoute: AuthenticatedCreateRoomRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRouteWithChildren,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface MessagesRouteChildren {
  MessagesPeerIdRoute: typeof MessagesPeerIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesPeerIdRoute: MessagesPeerIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoute: RoomsRoute,
  SplashRoute: SplashRoute,
  ApiAgoraTokenRoute: ApiAgoraTokenRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
