import { Mic, MicOff, Plus, Heart } from "lucide-react";
import { cn } from "@/lib/utils";
import type { RoomSeat } from "./types";
import { formatCount } from "./types";

interface SeatProps { seat: RoomSeat; onTap: (seat: RoomSeat) => void; }

export function Seat({ seat, onTap }: SeatProps) {
  const { user, seatNumber } = seat;
  if (!user) return <button data-seat data-seat-id={seatNumber} data-jalwa-live-component="voice.seat" data-jalwa-live-instance={seatNumber - 1} data-jalwa-live-source="SeatsGrid" onClick={() => onTap(seat)} className="group relative flex min-h-[82px] flex-col items-center justify-center gap-1 rounded-[22px] border border-dashed border-white/15 bg-white/[0.045] px-2 py-2.5 shadow-[inset_0_1px_0_rgba(255,255,255,.08)] transition-all duration-200 hover:border-fuchsia-300/50 hover:bg-fuchsia-500/[0.08] active:scale-[.97]" aria-label={`Join seat ${seatNumber}`}><span className="absolute left-2 top-2 grid h-5 w-5 place-items-center rounded-full bg-black/45 text-[9px] font-bold text-white/55 ring-1 ring-white/10">{seatNumber}</span><span className="flex h-12 w-12 items-center justify-center rounded-full border border-white/10 bg-white/[0.05] text-white/40 shadow-inner"><Plus className="h-5 w-5" /></span><span className="text-[10px] font-semibold text-white/45">No.{seatNumber}</span><span className="flex items-center gap-0.5 text-[9px] text-white/25"><Heart className="h-2.5 w-2.5" />0</span></button>;
  const speaking = user.mic === "speaking"; const muted = user.mic === "muted"; const micOff = user.mic === "off"; const isMuted = muted || micOff;
  return <button data-seat data-seat-id={seatNumber} data-jalwa-live-component="voice.seat" data-jalwa-live-instance={seatNumber - 1} data-jalwa-live-source="SeatsGrid" onClick={() => onTap(seat)} className={cn("group relative flex min-h-[112px] flex-col items-center justify-center gap-1.5 overflow-hidden rounded-[22px] border px-2 py-2.5 transition-all duration-200 active:scale-[.97]", "bg-gradient-to-b from-white/[0.10] via-white/[0.045] to-black/45", speaking ? "border-fuchsia-300 shadow-[0_0_28px_-5px_rgba(236,72,153,.9),inset_0_1px_0_rgba(255,255,255,.16)]" : "border-violet-300/30 shadow-[0_12px_30px_-18px_rgba(124,58,237,.8),inset_0_1px_0_rgba(255,255,255,.10)] hover:border-cyan-200/55")} aria-label={`Seat ${seatNumber}, ${user.name}`}>
    <span className="pointer-events-none absolute inset-x-3 top-0 h-px bg-gradient-to-r from-transparent via-white/35 to-transparent" /><span className="pointer-events-none absolute -left-px -top-px h-4 w-4 rounded-tl-[22px] border-l-2 border-t-2 border-cyan-300/70" /><span className="pointer-events-none absolute -right-px -bottom-px h-4 w-4 rounded-br-[22px] border-b-2 border-r-2 border-fuchsia-300/70" />
    <span className="absolute left-2 top-2 z-10 grid h-5 w-5 place-items-center rounded-full bg-black/60 text-[9px] font-black text-white/80 ring-1 ring-white/15">{seatNumber}</span>
    <span className="relative"><span className={cn("absolute inset-0 -m-2 rounded-full", speaking && "animate-ping bg-fuchsia-500/35")} /><span className={cn("relative flex h-14 w-14 items-center justify-center overflow-hidden rounded-full border-2 bg-slate-900/50 shadow-lg", speaking ? "border-fuchsia-300 ring-4 ring-fuchsia-400/15" : "border-cyan-300/45 ring-2 ring-white/5")}><img src={user.avatarUrl} alt={user.name} className="h-full w-full object-cover" draggable={false} /></span><span className={cn("absolute -bottom-0.5 -right-0.5 flex h-5 w-5 items-center justify-center rounded-full border-2 border-slate-950", isMuted ? "bg-red-500 text-white" : "bg-emerald-500 text-white")}>{isMuted ? <MicOff className="h-2.5 w-2.5" /> : <Mic className="h-2.5 w-2.5" />}</span></span>
    <span className="max-w-full truncate text-[11px] font-bold text-white/95">{user.name}</span><span className="flex items-center gap-0.5 text-[9px] font-medium text-white/45"><Heart className="h-2.5 w-2.5 fill-current text-pink-400/80" />{formatCount(user.popularity)}</span>
  </button>;
}

interface SeatsGridProps { seats: RoomSeat[]; onSeatTap: (seat: RoomSeat) => void; center: React.ReactNode; }
export function SeatsGrid({ seats, onSeatTap, center }: SeatsGridProps) {
  const left = seats.slice(0, 8), right = seats.slice(8, 16), bottom = seats.slice(16, 20);
  return <div data-seat-grid data-jalwa-live-component="voice.seat-area" data-jalwa-live-source="SeatsGrid" className="mx-auto flex w-full max-w-[430px] min-w-0 flex-col gap-2.5 px-1"><div className="grid w-full min-w-0 grid-cols-[1fr_1.35fr_1fr] items-start gap-2"><div className="grid min-w-0 grid-cols-2 gap-2">{left.map(s => <Seat key={s.seatNumber} seat={s} onTap={onSeatTap} />)}</div><div data-jalwa-live-component="voice.host" className="min-w-0 rounded-[28px]">{center}</div><div className="grid min-w-0 grid-cols-2 gap-2">{right.map(s => <Seat key={s.seatNumber} seat={s} onTap={onSeatTap} />)}</div></div><div className="grid w-full min-w-0 grid-cols-4 gap-2">{bottom.map(s => <Seat key={s.seatNumber} seat={s} onTap={onSeatTap} />)}</div></div>;
}
