import { Mic, MicOff, Plus, Heart } from "lucide-react";
import { cn } from "@/lib/utils";
import type { RoomSeat } from "./types";
import { formatCount } from "./types";

interface SeatProps { seat: RoomSeat; onTap: (seat: RoomSeat) => void; }

export function Seat({ seat, onTap }: SeatProps) {
  const { user, seatNumber } = seat;
  if (!user) return <button data-seat data-seat-id={seatNumber} data-jalwa-live-component="voice.seat" data-jalwa-live-instance={seatNumber - 1} data-jalwa-live-source="SeatsGrid" onClick={() => onTap(seat)} className="group relative flex min-w-0 w-full flex-col items-center justify-center gap-[clamp(2px,0.9vw,5px)] rounded-[clamp(12px,3.4vw,18px)] border border-dashed border-white/15 bg-white/[0.045] px-[clamp(2px,1vw,6px)] py-[clamp(7px,1.8vw,11px)] shadow-[inset_0_1px_0_rgba(255,255,255,.08)] transition-all duration-200 hover:border-fuchsia-300/50 hover:bg-fuchsia-500/[0.08] active:scale-[.97]" aria-label={`Join seat ${seatNumber}`}><span className="absolute left-[clamp(4px,1.1vw,7px)] top-[clamp(4px,1.1vw,7px)] grid h-[clamp(15px,4.1vw,19px)] w-[clamp(15px,4.1vw,19px)] place-items-center rounded-full bg-black/50 text-[clamp(8px,2.1vw,10px)] font-bold text-white/55 ring-1 ring-white/10">{seatNumber}</span><span className="flex h-[clamp(34px,9.8vw,50px)] w-[clamp(34px,9.8vw,50px)] items-center justify-center rounded-full border border-white/10 bg-white/[0.05] text-white/40 shadow-inner"><Plus className="h-[clamp(15px,4.2vw,21px)] w-[clamp(15px,4.2vw,21px)]" /></span><span className="max-w-full truncate text-[clamp(8px,2.35vw,11px)] font-semibold leading-none text-white/45">No.{seatNumber}</span><span className="flex items-center gap-0.5 text-[clamp(7px,1.9vw,9px)] leading-none text-white/25"><Heart className="h-[clamp(8px,2.2vw,11px)] w-[clamp(8px,2.2vw,11px)]" />0</span></button>;

  const speaking = user.mic === "speaking"; const muted = user.mic === "muted"; const micOff = user.mic === "off"; const isMuted = muted || micOff;
  return <button data-seat data-seat-id={seatNumber} data-jalwa-live-component="voice.seat" data-jalwa-live-instance={seatNumber - 1} data-jalwa-live-source="SeatsGrid" onClick={() => onTap(seat)} className={cn("group relative flex min-w-0 w-full flex-col items-center justify-center gap-[clamp(2px,0.9vw,5px)] overflow-hidden rounded-[clamp(12px,3.4vw,18px)] border-2 px-[clamp(2px,1vw,6px)] py-[clamp(7px,1.8vw,11px)] transition-all duration-200 active:scale-[.97]", "bg-gradient-to-b from-white/[0.10] via-white/[0.045] to-black/45", speaking ? "border-fuchsia-300 shadow-[0_0_28px_-5px_rgba(236,72,153,.9),inset_0_1px_0_rgba(255,255,255,.16)]" : "border-violet-300/30 shadow-[0_12px_30px_-18px_rgba(124,58,237,.8),inset_0_1px_0_rgba(255,255,255,.10)] hover:border-cyan-200/55")} aria-label={`Seat ${seatNumber}, ${user.name}`}>
    <span className="pointer-events-none absolute inset-x-3 top-0 h-px bg-gradient-to-r from-transparent via-white/35 to-transparent" /><span className="pointer-events-none absolute -left-px -top-px h-[clamp(8px,2.4vw,13px)] w-[clamp(8px,2.4vw,13px)] rounded-tl-[clamp(12px,3.4vw,18px)] border-l-2 border-t-2 border-cyan-300/70" /><span className="pointer-events-none absolute -right-px -bottom-px h-[clamp(8px,2.4vw,13px)] w-[clamp(8px,2.4vw,13px)] rounded-br-[clamp(12px,3.4vw,18px)] border-b-2 border-r-2 border-fuchsia-300/70" />
    <span className="absolute left-[clamp(4px,1.1vw,7px)] top-[clamp(4px,1.1vw,7px)] z-10 grid h-[clamp(15px,4.1vw,19px)] w-[clamp(15px,4.1vw,19px)] place-items-center rounded-full bg-black/60 text-[clamp(8px,2.1vw,10px)] font-black text-white/80 ring-1 ring-white/15">{seatNumber}</span>
    <span className="relative"><span className={cn("absolute inset-0 -m-[clamp(4px,1.5vw,8px)] rounded-full", speaking && "animate-ping bg-fuchsia-500/35")} /><span className={cn("relative flex h-[clamp(42px,12.3vw,60px)] w-[clamp(42px,12.3vw,60px)] items-center justify-center overflow-hidden rounded-full border-2 bg-slate-900/50 shadow-lg", speaking ? "border-fuchsia-300 ring-4 ring-fuchsia-400/15" : "border-cyan-300/45 ring-2 ring-white/5")}><img src={user.avatarUrl} alt={user.name} className="h-full w-full object-cover" draggable={false} /></span><span className={cn("absolute -bottom-0.5 -right-0.5 flex h-[clamp(16px,4.4vw,21px)] w-[clamp(16px,4.4vw,21px)] items-center justify-center rounded-full border-2 border-slate-950", isMuted ? "bg-red-500 text-white" : "bg-emerald-500 text-white")}>{isMuted ? <MicOff className="h-[clamp(8px,2.4vw,12px)] w-[clamp(8px,2.4vw,12px)]" /> : <Mic className="h-[clamp(8px,2.4vw,12px)] w-[clamp(8px,2.4vw,12px)]" />}</span></span>
    <span className="w-full truncate text-[clamp(8px,2.45vw,11px)] font-bold leading-tight text-white/95">{user.name}</span><span className="flex items-center gap-0.5 text-[clamp(7px,2vw,9px)] font-medium leading-none text-white/45"><Heart className="h-[clamp(8px,2.2vw,11px)] w-[clamp(8px,2.2vw,11px)] fill-current text-pink-400/80" />{formatCount(user.popularity)}</span>
  </button>;
}

interface SeatsGridProps { seats: RoomSeat[]; onSeatTap: (seat: RoomSeat) => void; center: React.ReactNode; }

/** Master mobile composition: 390px reference proportions, kept as one grid at every viewport width. */
export function SeatsGrid({ seats, onSeatTap, center }: SeatsGridProps) {
  const normalized = Array.from({ length: 20 }, (_, index) => seats[index] ?? ({ seatNumber: index + 1, user: null } as RoomSeat));
  const left = normalized.slice(0, 8), right = normalized.slice(8, 16), bottom = normalized.slice(16, 20);
  return <div data-seat-grid data-jalwa-live-component="voice.seat-area" data-jalwa-live-source="SeatsGrid" className="mx-auto flex w-full min-w-0 max-w-[100vw] flex-col gap-[clamp(5px,1.6vw,10px)] overflow-hidden px-[clamp(4px,1.3vw,8px)]"><div className="grid w-full min-w-0 grid-cols-[minmax(0,1fr)_minmax(0,1.28fr)_minmax(0,1fr)] items-stretch gap-[clamp(4px,1.3vw,8px)]"><div className="grid min-w-0 grid-cols-2 content-start gap-[clamp(4px,1.3vw,8px)]">{left.map(s => <Seat key={s.seatNumber} seat={s} onTap={onSeatTap} />)}</div><div data-jalwa-live-component="voice.host" className="flex min-w-0 items-center justify-center">{center}</div><div className="grid min-w-0 grid-cols-2 content-start gap-[clamp(4px,1.3vw,8px)]">{right.map(s => <Seat key={s.seatNumber} seat={s} onTap={onSeatTap} />)}</div></div><div className="grid w-full min-w-0 grid-cols-4 gap-[clamp(4px,1.3vw,8px)]">{bottom.map(s => <Seat key={s.seatNumber} seat={s} onTap={onSeatTap} />)}</div></div>;
}
