import { useState } from "react";
import { Rocket, Calendar, Megaphone, Home, Gift, Gamepad2, MessageCircle, User, Mic, MicOff, Smile, Send, MoreHorizontal } from "lucide-react";
import { cn } from "@/lib/utils";
import type { RoomState } from "@/types/room";
import { RoomHeader } from "./RoomHeader";
import { SeatGrid } from "./SeatGrid";

const OCTAGON = { clipPath: "polygon(30% 0%, 70% 0%, 100% 30%, 100% 70%, 70% 100%, 30% 100%, 0% 70%, 0% 30%)" } as const;

interface VoiceRoomScreenProps { room: RoomState; roomCode: string; onlineCount: number; micOn: boolean; isHost: boolean; mySeatIndex: number | null; popularityPct: number; topGifterName?: string | null; topGifterCoins?: number; announcement?: string | null; onOpenChat: () => void; onOpenPrivateChat: () => void; onOpenGift: () => void; onOpenMore: () => void; onToggleMic: () => void; onSeatTap: (index: number) => void; onJoinSeat: (index: number) => void; onHostTap?: () => void; onReport: () => void; onShare: () => void; onExit: () => void; onHome: () => void; onRanking: () => void; onOpenGames: () => void; }

export const VoiceRoomScreen = ({ room, roomCode, onlineCount, micOn, isHost, mySeatIndex, popularityPct, topGifterName, topGifterCoins, announcement, onOpenChat, onOpenPrivateChat, onOpenGift, onOpenMore, onToggleMic, onSeatTap, onJoinSeat, onHostTap, onReport, onShare, onExit, onHome, onRanking, onOpenGames }: VoiceRoomScreenProps) => {
  const [draft] = useState("");
  const canSpeak = isHost || mySeatIndex !== null;
  const tap = (handler: () => void) => (e: React.MouseEvent<HTMLButtonElement>) => { e.preventDefault(); e.stopPropagation(); handler(); };
  const buttonClass = "touch-manipulation pointer-events-auto select-none";
  return <main className="relative z-50 pointer-events-auto touch-manipulation mx-auto flex h-[100dvh] min-h-[100dvh] w-full max-w-[480px] flex-col overflow-hidden overscroll-none bg-[#08050c] text-white shadow-2xl">
    <div className="pointer-events-none absolute inset-0" />
    <RoomHeader room={room} roomCode={roomCode} onlineCount={onlineCount} topGifterName={topGifterName} topGifterCoins={topGifterCoins} onReport={onReport} onShare={onShare} onExit={onExit} onHome={onHome} onRanking={onRanking} />
    <div className="relative z-10 flex min-h-0 flex-1 flex-col gap-2 overflow-hidden pb-2">
      <SeatGrid seats={room.seats} host={room.host} micOn={micOn} onToggleMic={onToggleMic} onSeatTap={onSeatTap} onJoinSeat={onJoinSeat} onHostTap={onHostTap} />
      <div className="mx-2.5 flex shrink-0 items-center gap-2 overflow-hidden rounded-full border border-fuchsia-400/40 bg-gradient-to-r from-[#170a26] via-[#1c0a2e] to-[#170a26] py-1.5 pl-1 pr-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-fuchsia-500 to-violet-600 text-[11px]">📣</span><p className="min-w-0 flex-1 truncate text-xs text-white/70">{announcement || `Welcome to ${room.title} — be kind, have fun ✨`}</p><Rocket className="h-4 w-4 shrink-0 text-fuchsia-300" /></div>
      <div className="flex min-h-0 flex-1 gap-2 overflow-hidden px-2.5">
        <div className="flex min-h-0 flex-[1.9] flex-col overflow-hidden rounded-2xl border border-violet-400/30 bg-gradient-to-b from-white/[0.03] to-transparent"><div className="flex items-center gap-4 border-b border-white/10 px-2.5 pt-2"><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"relative pb-1.5 text-[12px] font-bold text-white")}>All<span className="absolute -bottom-px left-0 h-0.5 w-full rounded-full bg-fuchsia-400" /></button><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"pb-1.5 text-[12px] font-semibold text-white/60")}>Chat</button></div><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"flex flex-1 flex-col items-center justify-center gap-1.5 px-3 py-4 text-center text-white/35")}><MessageCircle className="h-7 w-7" /><p className="text-xs font-medium">No messages yet</p><p className="text-[10px]">Start the conversation</p></button><div className="flex items-center gap-2 border-t border-white/10 px-2 py-2"><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"flex min-w-0 flex-1 items-center gap-2 rounded-full border border-white/10 bg-black/50 px-3 py-1.5 text-left")}><span className="min-w-0 flex-1 truncate text-[12px] text-white/40">{draft.trim() ? draft : "Say something..."}</span><Smile className="h-3.5 w-3.5 shrink-0 text-white/50" /></button><button type="button" onClick={tap(onOpenChat)} aria-label="Send message" className={cn(buttonClass,"grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gradient-to-br from-fuchsia-500 to-violet-600 text-white")}><Send className="h-3.5 w-3.5" /></button></div></div>
        <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-hidden"><button type="button" onClick={tap(onRanking)} className={cn(buttonClass,"shrink-0 rounded-2xl border border-fuchsia-400/40 bg-gradient-to-b from-[#1a0a2e] to-[#0d0616] p-2.5 text-left")}><div className="mb-1.5 flex items-center gap-1.5 text-[11px] font-semibold text-white/90"><Rocket className="h-3.5 w-3.5 text-fuchsia-400" />Popularity</div><div className="rounded-full border border-fuchsia-400/30 bg-black/40 px-2 py-1 text-center text-[10px] font-black text-fuchsia-200">{popularityPct}%</div></button><button type="button" onClick={tap(onOpenGames)} className={cn(buttonClass,"shrink-0 rounded-2xl border border-violet-400/25 bg-white/[0.03] p-2.5 text-left")}><div className="mb-0.5 flex items-center gap-1.5 text-[11px] font-semibold text-white/85"><Calendar className="h-3.5 w-3.5 text-violet-400" />Events</div><p className="text-[10px] text-white/45">No active events</p></button><button type="button" onClick={tap(onOpenMore)} className={cn(buttonClass,"min-h-0 flex-1 overflow-hidden rounded-2xl border border-amber-400/25 bg-white/[0.03] p-2.5 text-left")}><div className="mb-0.5 flex items-center gap-1.5 text-[11px] font-semibold text-white/85"><Megaphone className="h-3.5 w-3.5 text-amber-400" />Announcement</div><p className="line-clamp-2 text-[10px] text-white/45">{announcement || "No announcement yet"}</p></button></div>
      </div>
    </div>
    <div className="relative z-20 flex shrink-0 items-end gap-2 border-t border-fuchsia-400/20 bg-black/90 px-2.5 py-2 pb-[calc(0.5rem+env(safe-area-inset-bottom))] backdrop-blur-md pointer-events-auto"><div className="flex flex-1 items-center justify-around rounded-2xl border border-white/10 bg-white/[0.03] px-1 py-1.5"><button type="button" onClick={tap(onHome)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><Home className="h-5 w-5" /><span className="text-[9px] font-semibold">Home</span></button><button type="button" onClick={tap(onOpenGift)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><Gift className="h-5 w-5" /><span className="text-[9px] font-semibold">Gifts</span></button><button type="button" onClick={tap(onOpenGames)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><Gamepad2 className="h-5 w-5" /><span className="text-[9px] font-semibold">Game</span></button></div>{canSpeak ? <button type="button" onClick={tap(onToggleMic)} aria-label="Toggle microphone" style={OCTAGON} className={cn(buttonClass,"flex h-14 w-14 shrink-0 items-center justify-center border-2 active:scale-90",micOn?"border-fuchsia-400 bg-gradient-to-b from-fuchsia-500 to-violet-700 shadow-[0_0_22px_-2px_rgba(232,60,220,0.9)]":"border-white/20 bg-white/10")}>{micOn?<Mic className="h-6 w-6"/>:<MicOff className="h-6 w-6 text-white/60"/>}</button>:<div className="h-14 w-14 shrink-0"/>}<div className="flex flex-1 items-center justify-around rounded-2xl border border-white/10 bg-white/[0.03] px-1 py-1.5"><button type="button" onClick={tap(onOpenPrivateChat)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><MessageCircle className="h-5 w-5"/><span className="text-[9px] font-semibold">Chat</span></button><button type="button" onClick={tap(onOpenMore)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><MoreHorizontal className="h-5 w-5"/><span className="text-[9px] font-semibold">More</span></button></div></div>
  </main>;
};