import { useMemo, useState } from "react";
import { Rocket, Calendar, Megaphone, Home, Gift, Gamepad2, MessageCircle, User, Mic, MicOff, Smile, Send, MoreHorizontal, Flag, Share2, Power, Trophy } from "lucide-react";
import { cn } from "@/lib/utils";
import type { RoomState } from "@/types/room";
import { RoomHeader } from "./RoomHeader";
import { SeatGrid } from "./SeatGrid";
import { GiftSheet, type GiftReceiver } from "@/components/GiftSheet";
import { RoomGamesSheet } from "@/components/room/RoomGamesSheet";

const OCTAGON = { clipPath: "polygon(30% 0%, 70% 0%, 100% 30%, 100% 70%, 70% 100%, 30% 100%, 0% 70%, 0% 30%)" } as const;

interface VoiceRoomScreenProps { room: RoomState; roomId: string; seatCount?: number; roomCode: string; onlineCount: number; micOn: boolean; isHost: boolean; mySeatIndex: number | null; popularityPct: number; topGifterName?: string | null; topGifterCoins?: number; announcement?: string | null; onOpenChat: () => void; onOpenPrivateChat: () => void; onOpenGift: () => void; onOpenMore: () => void; onToggleMic: () => void; onSeatTap: (index: number) => void; onJoinSeat: (index: number) => void; onHostTap?: () => void; onReport: () => void; onShare: () => void; onExit: () => void; onHome: () => void; onRanking: () => void; onOpenGames: () => void; }

export const VoiceRoomScreen = ({ room, roomId, seatCount, roomCode, onlineCount, micOn, isHost, mySeatIndex, popularityPct, topGifterName, topGifterCoins, announcement, onOpenChat, onOpenPrivateChat, onOpenGift, onOpenMore, onToggleMic, onSeatTap, onJoinSeat, onHostTap, onReport, onShare, onExit, onHome, onRanking, onOpenGames }: VoiceRoomScreenProps) => {
  const [draft] = useState("");
  const [giftOpen, setGiftOpen] = useState(false);
  const [gamesOpen, setGamesOpen] = useState(false);
  const [moreOpen, setMoreOpen] = useState(false);
  const canSpeak = isHost || mySeatIndex !== null;
  const tap = (handler: () => void) => (e: React.MouseEvent<HTMLButtonElement>) => { e.preventDefault(); e.stopPropagation(); handler(); };
  const buttonClass = "touch-manipulation pointer-events-auto select-none";
  const receivers = useMemo<GiftReceiver[]>(() => {
    const seated = room.seats.filter(s => s.user && s.user.id !== room.host.id).map(s => ({ id: s.user!.id, username: s.user!.username, avatar: s.user!.avatar }));
    return room.host.id ? [{ id: room.host.id, username: room.host.username, avatar: room.host.avatar }, ...seated] : seated;
  }, [room]);

  const openGifts = () => { setGiftOpen(true); onOpenGift(); };
  const openGames = () => { setGamesOpen(true); onOpenGames(); };
  const openMore = () => { setMoreOpen(true); onOpenMore(); };

  return <main className="relative z-50 pointer-events-auto touch-manipulation overscroll-none mx-auto flex h-[100dvh] min-h-[100dvh] w-full max-w-none sm:max-w-[480px] flex-col overflow-hidden overscroll-none bg-[#08050c] text-white shadow-2xl">
    <div className="pointer-events-none absolute inset-0" />
    <RoomHeader room={room} roomCode={roomCode} onlineCount={onlineCount} topGifterName={topGifterName} topGifterCoins={topGifterCoins} onReport={onReport} onShare={onShare} onExit={onExit} onHome={onHome} onRanking={onRanking} />
    <div className="relative z-10 flex min-h-0 flex-1 flex-col gap-2 overflow-hidden pb-2">
      <SeatGrid seats={room.seats} seatCount={seatCount} host={room.host} micOn={micOn} onToggleMic={onToggleMic} onSeatTap={onSeatTap} onJoinSeat={onJoinSeat} onHostTap={onHostTap} />
      <div className="mx-2.5 flex shrink-0 items-center gap-2 overflow-hidden rounded-full border border-fuchsia-400/40 bg-gradient-to-r from-[#170a26] via-[#1c0a2e] to-[#170a26] py-1.5 pl-1 pr-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-fuchsia-500 to-violet-600 text-[11px]">📣</span><p className="min-w-0 flex-1 truncate text-xs text-white/70">{announcement || `Welcome to ${room.title} — be kind, have fun ✨`}</p><Rocket className="h-4 w-4 shrink-0 text-fuchsia-300" /></div>
      <div className="flex min-h-0 flex-1 gap-2 overflow-hidden px-2.5">
        <div className="flex min-h-0 flex-[1.9] flex-col overflow-hidden rounded-2xl border border-violet-400/30 bg-gradient-to-b from-white/[0.03] to-transparent"><div className="flex items-center gap-4 border-b border-white/10 px-2.5 pt-2"><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"relative pb-1.5 text-[12px] font-bold text-white")}>All<span className="absolute -bottom-px left-0 h-0.5 w-full rounded-full bg-fuchsia-400" /></button><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"pb-1.5 text-[12px] font-semibold text-white/60")}>Chat</button></div><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"flex flex-1 flex-col items-center justify-center gap-1.5 px-3 py-4 text-center text-white/35")}><MessageCircle className="h-7 w-7" /><p className="text-xs font-medium">No messages yet</p><p className="text-[10px]">Start the conversation</p></button><div className="flex items-center gap-2 border-t border-white/10 px-2 py-2"><button type="button" onClick={tap(onOpenChat)} className={cn(buttonClass,"flex min-w-0 flex-1 items-center gap-2 rounded-full border border-white/10 bg-black/50 px-3 py-1.5 text-left")}><span className="min-w-0 flex-1 truncate text-[12px] text-white/40">{draft.trim() ? draft : "Say something..."}</span><Smile className="h-3.5 w-3.5 shrink-0 text-white/50" /></button><button type="button" onClick={tap(onOpenChat)} aria-label="Send message" className={cn(buttonClass,"grid h-8 w-8 shrink-0 place-items-center rounded-full bg-gradient-to-br from-fuchsia-500 to-violet-600 text-white")}><Send className="h-3.5 w-3.5" /></button></div></div>
        <div className="flex min-h-0 flex-1 flex-col gap-2 overflow-hidden"><button type="button" onClick={tap(onRanking)} className={cn(buttonClass,"shrink-0 rounded-2xl border border-fuchsia-400/40 bg-gradient-to-b from-[#1a0a2e] to-[#0d0616] p-2.5 text-left")}><div className="mb-1.5 flex items-center gap-1.5 text-[11px] font-semibold text-white/90"><Rocket className="h-3.5 w-3.5 text-fuchsia-400" />Popularity</div><div className="rounded-full border border-fuchsia-400/30 bg-black/40 px-2 py-1 text-center text-[10px] font-black text-fuchsia-200">{popularityPct}%</div></button><button type="button" onClick={tap(openGames)} className={cn(buttonClass,"shrink-0 rounded-2xl border border-violet-400/25 bg-white/[0.03] p-2.5 text-left")}><div className="mb-0.5 flex items-center gap-1.5 text-[11px] font-semibold text-white/85"><Calendar className="h-3.5 w-3.5 text-violet-400" />Events</div><p className="text-[10px] text-white/45">Open Games</p></button><button type="button" onClick={tap(openMore)} className={cn(buttonClass,"min-h-0 flex-1 overflow-hidden rounded-2xl border border-amber-400/25 bg-white/[0.03] p-2.5 text-left")}><div className="mb-0.5 flex items-center gap-1.5 text-[11px] font-semibold text-white/85"><Megaphone className="h-3.5 w-3.5 text-amber-400" />Announcement</div><p className="line-clamp-2 text-[10px] text-white/45">{announcement || "Tap for More"}</p></button></div>
      </div>
    </div>
    <div className="relative z-20 flex shrink-0 items-end gap-2 border-t border-fuchsia-400/20 bg-black/95 px-2.5 py-2 pb-[calc(0.5rem+env(safe-area-inset-bottom))] pointer-events-auto"><div className="flex flex-1 items-center justify-around rounded-2xl border border-white/10 bg-white/[0.03] px-1 py-1.5"><button type="button" onClick={tap(onHome)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><Home className="h-5 w-5" /><span className="text-[9px] font-semibold">Home</span></button><button type="button" onClick={tap(openGifts)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><Gift className="h-5 w-5" /><span className="text-[9px] font-semibold">Gifts</span></button><button type="button" onClick={tap(openGames)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><Gamepad2 className="h-5 w-5" /><span className="text-[9px] font-semibold">Game</span></button></div>{canSpeak ? <button type="button" onClick={tap(onToggleMic)} aria-label="Toggle microphone" style={OCTAGON} className={cn(buttonClass,"flex h-14 w-14 shrink-0 items-center justify-center border-2 active:scale-90",micOn?"border-fuchsia-400 bg-gradient-to-b from-fuchsia-500 to-violet-700 shadow-[0_0_22px_-2px_rgba(232,60,220,0.9)]":"border-white/20 bg-white/10")}>{micOn?<Mic className="h-6 w-6"/>:<MicOff className="h-6 w-6 text-white/60"/>}</button>:<div className="h-14 w-14 shrink-0"/>}<div className="flex flex-1 items-center justify-around rounded-2xl border border-white/10 bg-white/[0.03] px-1 py-1.5"><button type="button" onClick={tap(onOpenPrivateChat)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><MessageCircle className="h-5 w-5"/><span className="text-[9px] font-semibold">Chat</span></button><button type="button" onClick={tap(openMore)} className={cn(buttonClass,"flex flex-col items-center gap-0.5 px-1 text-white/70")}><MoreHorizontal className="h-5 w-5"/><span className="text-[9px] font-semibold">More</span></button></div></div>

    <GiftSheet open={giftOpen} onClose={() => setGiftOpen(false)} roomId={roomId} receivers={receivers} />
    <RoomGamesSheet open={gamesOpen} onClose={() => setGamesOpen(false)} onOpenNative={(slug) => { setGamesOpen(false); onOpenGames(); window.dispatchEvent(new CustomEvent("jalwa:open-game", { detail: { slug, roomId } })); }} />
    {moreOpen && <><div className="fixed inset-0 z-[2147483000] bg-black/60 touch-none" onClick={() => setMoreOpen(false)} /><div className="fixed bottom-0 left-1/2 z-[2147483001] w-full max-w-[480px] -translate-x-1/2 rounded-t-3xl border-t border-fuchsia-400/30 bg-[#0d0616] p-4 pb-[calc(1rem+env(safe-area-inset-bottom))] shadow-2xl"><div className="mx-auto mb-3 h-1 w-10 rounded-full bg-white/20" /><h3 className="mb-3 text-sm font-black">More</h3><div className="grid grid-cols-2 gap-2"><button type="button" onClick={tap(onReport)} className="flex items-center gap-2 rounded-xl bg-white/5 p-3 text-left text-xs"><Flag className="h-4 w-4"/>Report</button><button type="button" onClick={tap(onShare)} className="flex items-center gap-2 rounded-xl bg-white/5 p-3 text-left text-xs"><Share2 className="h-4 w-4"/>Share</button><button type="button" onClick={tap(onRanking)} className="flex items-center gap-2 rounded-xl bg-white/5 p-3 text-left text-xs"><Trophy className="h-4 w-4"/>Ranking</button><button type="button" onClick={tap(onExit)} className="flex items-center gap-2 rounded-xl bg-red-500/15 p-3 text-left text-xs text-red-300"><Power className="h-4 w-4"/>Exit Room</button></div></div></>}
  </main>;
};