import { useEffect, useMemo, useState } from "react";
import type { AppComponentNode, AppPageConfig, ComponentStyle, DeviceKind } from "@/lib/app-customization/schema";
import { flattenLiveRoomRegistry, type LiveRoomComponent } from "@/lib/app-customization/live-room-registry";
import { presetsForRoom } from "@/lib/app-customization/live-room-presets";
import { Eye, EyeOff, GripVertical, Lock, Plus, Save, Unlock } from "lucide-react";

export type LiveRoomKind = "voice-room" | "video-room" | "pk-battle";
export type LiveRoomState = "empty" | "normal" | "full" | "speaking" | "gift" | "chat" | "settings" | "camera-on" | "camera-off" | "fullscreen" | "multiple" | "waiting" | "match-found" | "countdown" | "battle-running" | "battle-ending" | "winner" | "loser";
type RegistryKind = "voice" | "video" | "pk";
const rk = (k: LiveRoomKind): RegistryKind => k === "voice-room" ? "voice" : k === "video-room" ? "video" : "pk";
const label = (k: LiveRoomKind) => k === "voice-room" ? "Voice Room" : k === "video-room" ? "Video Room" : "PK Battle";
const STATES: Record<LiveRoomKind, { value: LiveRoomState; label: string }[]> = {
  "voice-room": [["empty","Empty"],["normal","Normal"],["full","Full"],["speaking","Host Speaking"],["gift","Gift Received"],["chat","Chat Open"],["settings","Settings Open"]].map(([value,label]) => ({ value: value as LiveRoomState, label })),
  "video-room": [["empty","Empty"],["normal","Normal"],["camera-on","Camera On"],["camera-off","Camera Off"],["fullscreen","Fullscreen"],["multiple","Multiple Participants"],["chat","Chat Open"],["gift","Gift Popup"]].map(([value,label]) => ({ value: value as LiveRoomState, label })),
  "pk-battle": [["waiting","Waiting"],["match-found","Match Found"],["countdown","Countdown"],["battle-running","Battle Running"],["gift","Gift Received"],["battle-ending","Battle Ending"],["winner","Winner"],["loser","Loser"]].map(([value,label]) => ({ value: value as LiveRoomState, label })),
};
const DEFAULT_COUNTS: Record<string, number> = { "voice.seat": 20, "video.participant": 6 };
const DEVICES: { value: DeviceKind; label: string }[] = [{value:"mobile",label:"Mobile"},{value:"tablet",label:"Tablet"},{value:"desktop",label:"Desktop"}];
const EDITABLE: (keyof ComponentStyle)[] = ["x","y","width","height","zIndex","borderRadius","fontSize","fontWeight","lineHeight","letterSpacing","background","color","border","boxShadow","opacity","gap","padding","margin","objectFit","objectPosition"];
function clone(c: AppPageConfig): AppPageConfig { return structuredClone(c); }
function nodeFor(c: LiveRoomComponent, kind: LiveRoomKind, state: LiveRoomState, i: number): AppComponentNode { return { id: `${c.id}-${crypto.randomUUID()}`, type: "custom", name: c.label, visible: true, locked: false, props: { componentId: c.id, componentType: c.runtimeType ?? c.type, label: c.label, roomType: kind, roomState: state, instanceIndex: i, stateful: true, registryVersion: 2 }, style: {}, responsive: { mobile: {style:{}}, tablet: {style:{}}, desktop: {style:{}} } }; }
function syncConfig(config: AppPageConfig, kind: LiveRoomKind, state: LiveRoomState): AppPageConfig { const next = clone(config); const registry = flattenLiveRoomRegistry(rk(kind)).slice(1); const nodes = next.sections.filter(n => n.props?.roomType === kind); for (const c of registry) { const current = nodes.filter(n => n.props?.componentId === c.id).length; const wanted = c.repeatable ? (DEFAULT_COUNTS[c.id] ?? 1) : 1; if (current < wanted) for (let i=current;i<wanted;i++) next.sections.push(nodeFor(c,kind,state,i)); } return next; }
function deviceStyle(node: AppComponentNode, device: DeviceKind): ComponentStyle { return node.responsive?.[device]?.style ?? node.style ?? {}; }

export function LiveRoomStudioPanel({ pageKey, config, onChange, onSaveDraft, onPublish }: { pageKey: LiveRoomKind; config: AppPageConfig; onChange: (c: AppPageConfig) => void; onSaveDraft?: () => void; onPublish?: () => void }) {
  const [kind,setKind]=useState(pageKey); const [state,setState]=useState<LiveRoomState>("normal"); const [device,setDevice]=useState<DeviceKind>("desktop"); const [selectedId,setSelectedId]=useState<string|null>(null); const [libraryOpen,setLibraryOpen]=useState(false);
  const registry=useMemo(()=>flattenLiveRoomRegistry(rk(kind)).slice(1),[kind]); const nodes=useMemo(()=>config.sections.filter(n=>n.props?.roomType===kind),[config.sections,kind]); const selected=nodes.find(n=>n.id===selectedId)??null; const selectedComponent=registry.find(c=>c.id===selected?.props?.componentId)??null; const selectedStyle=selected?deviceStyle(selected,device):{};
  useEffect(()=>{setKind(pageKey);setSelectedId(null)},[pageKey]);
  useEffect(()=>{const h=(e:MessageEvent)=>{if(e.data?.type==="jalwa-live-select"&&typeof e.data.nodeId==="string")setSelectedId(e.data.nodeId);if(e.data?.type==="jalwa-live-focus"&&typeof e.data.nodeId==="string")setSelectedId(e.data.nodeId);if(e.data?.type==="jalwa-live-move"&&typeof e.data.nodeId==="string"){const n=config.sections.find(x=>x.id===e.data.nodeId);if(!n)return;const d=(e.data.device as DeviceKind)||device;const next=clone(config);next.sections=next.sections.map(x=>x.id===e.data.nodeId?{...x,responsive:{...x.responsive,[d]:{...x.responsive?.[d],style:{...deviceStyle(x,d),x:Number(e.data.x)||0,y:Number(e.data.y)||0}}}}:x);onChange(next);setSelectedId(e.data.nodeId);}};window.addEventListener("message",h);return()=>window.removeEventListener("message",h)},[config,onChange,device]);
  useEffect(()=>{if(!selected)return;window.postMessage({type:"jalwa-live-studio-style",nodeId:selected.id,device,style:selectedStyle,visible:selected.visible!==false,locked:selected.locked===true},"*")},[selected,selectedStyle,device]);
  const sync=()=>{const next=syncConfig(config,kind,state);onChange(next);const first=next.sections.find(n=>n.props?.roomType===kind);if(first)setSelectedId(first.id)};
  const add=(c:LiveRoomComponent)=>{const next=clone(config);const count=next.sections.filter(n=>n.props?.roomType===kind&&n.props?.componentId===c.id).length;const n=nodeFor(c,kind,state,count);next.sections.push(n);onChange(next);setSelectedId(n.id)};
  const patch=(p:Partial<AppComponentNode>)=>{if(!selected)return;const next=clone(config);next.sections=next.sections.map(n=>n.id===selected.id?{...n,...p}:n);onChange(next)};
  const style=(key:keyof ComponentStyle,value:string)=>{if(!selected)return;const next=clone(config);next.sections=next.sections.map(n=>n.id===selected.id?{...n,responsive:{...n.responsive,[device]:{...n.responsive?.[device],style:{...deviceStyle(n,device),[key]:value}}}}:n);onChange(next)};
  const applyPreset=(presetId:string)=>{const p=presetsForRoom(rk(kind)).find(x=>x.id===presetId);if(!p)return;let next=clone(config);next.sections=next.sections.filter(n=>n.props?.roomType!==kind);if(p.repeatable){const c=registry.find(x=>x.id===p.repeatable?.componentId);if(c)for(let i=0;i<p.repeatable.count;i++)next.sections.push(nodeFor(c,kind,state,i));}onChange(next);setSelectedId(null)};
  return <div className="space-y-3">
    <div className="grid gap-2 sm:grid-cols-3">{(["voice-room","video-room","pk-battle"] as LiveRoomKind[]).map(k=><button key={k} onClick={()=>{setKind(k);setSelectedId(null)}} className={`rounded-lg border px-3 py-2 text-left text-xs font-semibold ${kind===k?"bg-primary text-primary-foreground":"hover:bg-muted"}`}>{label(k)}</button>)}</div>
    <div className="grid gap-2 sm:grid-cols-3"><label className="text-[10px] font-semibold uppercase text-muted-foreground">Room State<select value={state} onChange={e=>setState(e.target.value as LiveRoomState)} className="mt-1 w-full rounded-lg border bg-background p-2 text-xs">{STATES[kind].map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label className="text-[10px] font-semibold uppercase text-muted-foreground">Editing Device<select value={device} onChange={e=>setDevice(e.target.value as DeviceKind)} className="mt-1 w-full rounded-lg border bg-background p-2 text-xs">{DEVICES.map(d=><option key={d.value} value={d.value}>{d.label}</option>)}</select></label><label className="text-[10px] font-semibold uppercase text-muted-foreground">Layout Preset<select onChange={e=>e.target.value&&applyPreset(e.target.value)} defaultValue="" className="mt-1 w-full rounded-lg border bg-background p-2 text-xs"><option value="">Choose preset…</option>{presetsForRoom(rk(kind)).map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label></div>
    <div className="flex gap-2"><button onClick={sync} className="flex-1 rounded-lg border px-3 py-2 text-xs">Sync actual components</button><button onClick={()=>setLibraryOpen(v=>!v)} className="rounded-lg border px-3 py-2 text-xs"><Plus className="mr-1 inline h-3.5 w-3.5"/>Library</button></div>
    {libraryOpen&&<div className="rounded-lg border bg-muted/20 p-2"><div className="mb-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Live Component Library</div><div className="grid gap-1 sm:grid-cols-2">{registry.map(c=><button key={c.id} onClick={()=>add(c)} className="rounded-md border bg-background px-2 py-1.5 text-left text-[11px] hover:bg-muted">{c.label}{c.repeatable?" • repeatable":""}</button>)}</div></div>}
    <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_330px]"><section className="rounded-lg border bg-background"><div className="border-b px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">REAL Component Tree · {nodes.length} mapped layers · {device}</div><div className="max-h-[520px] overflow-auto p-2">{registry.map(c=>{const matches=nodes.filter(n=>n.props?.componentId===c.id);return <div key={c.id} className="mb-1">{matches.length?matches.map((n,i)=><button key={n.id} onClick={()=>setSelectedId(n.id)} className={`flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-xs ${selectedId===n.id?"bg-primary/10 text-primary":"hover:bg-muted"}`}><GripVertical className="h-3 w-3 text-muted-foreground"/><span className="flex-1">{c.repeatable?`${c.label} ${i+1}`:c.label}</span><span className="text-[9px] text-emerald-600">REAL</span></button>):<div className="flex items-center gap-2 px-2 py-1 text-[11px] text-muted-foreground"><span className="flex-1">{c.label}</span><button onClick={()=>add(c)} className="text-primary">Add</button></div>})}</div>})}</div></section>
      <aside className="rounded-lg border bg-background p-3"><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Selected Layer · {device}</span>{selected&&<button onClick={()=>patch({locked:!selected.locked})}>{selected.locked?<Lock className="h-4 w-4"/>:<Unlock className="h-4 w-4"/>}</button>}</div>{selected?<div className="space-y-2"><div className="rounded-md bg-muted/40 p-2"><div className="text-xs font-semibold">{selectedComponent?.label??selected.name}</div><div className="text-[9px] text-muted-foreground">{String(selected.props?.componentId)} · instance {Number(selected.props?.instanceIndex??0)+1}</div></div><input value={selected.name??""} onChange={e=>patch({name:e.target.value})} className="w-full rounded border px-2 py-1.5 text-xs" placeholder="Layer name"/><div className="grid grid-cols-2 gap-2">{EDITABLE.map(k=><label key={String(k)} className="text-[9px] text-muted-foreground">{String(k)}<input value={String(selectedStyle[k]??"")} onChange={e=>style(k,e.target.value)} className="mt-1 w-full rounded border px-2 py-1.5 text-xs"/></label>)}</div><div className="flex gap-2"><button onClick={()=>patch({visible:selected.visible===false})} className="flex-1 rounded border px-2 py-1.5 text-xs">{selected.visible===false?<><Eye className="mr-1 inline h-3 w-3"/>Show</>:<><EyeOff className="mr-1 inline h-3 w-3"/>Hide</>}</button><button onClick={()=>patch({locked:!selected.locked})} className="flex-1 rounded border px-2 py-1.5 text-xs">{selected.locked?<Unlock className="mr-1 inline h-3 w-3"/>:<Lock className="mr-1 inline h-3 w-3"/>}{selected.locked?"Unlock":"Lock"}</button></div><div className="rounded border p-2"><div className="text-[9px] font-bold uppercase text-muted-foreground">Registry editable properties</div><div className="mt-1 flex flex-wrap gap-1">{(selectedComponent?.editable??[]).map(x=><span key={x} className="rounded bg-muted px-1.5 py-0.5 text-[9px]">{x}</span>)}</div></div></div>:<div className="py-8 text-center text-xs text-muted-foreground">Select a REAL layer or drag it directly inside the live preview.</div>}</aside></div>
    <div className="flex gap-2"><button onClick={onSaveDraft} className="flex-1 rounded-lg border px-3 py-2 text-xs"><Save className="mr-1 inline h-3.5 w-3.5"/>Save Draft</button><button onClick={onPublish} className="flex-1 rounded-lg bg-primary px-3 py-2 text-xs text-primary-foreground">Publish</button></div>
  </div>;
}
