import { useMemo } from "react";
import type { ComponentStyle, DeviceKind } from "@/lib/app-customization/schema";
import { LIVE_ROOM_VISUAL_CONTROLS, VISUAL_GROUP_LABELS, coerceVisualValue, type VisualControl } from "@/lib/app-customization/live-room-visual-controls";
import { Paintbrush, RotateCcw } from "lucide-react";

type Props={style:ComponentStyle;device:DeviceKind;onChange:(key:string,value:unknown)=>void;onReset:(keys:string[])=>void};
const fieldClass="mt-1 w-full rounded border bg-background px-2 py-1.5 text-xs";
const read=(style:ComponentStyle,key:string)=>String((style as Record<string,unknown>)[key]??"");

export function LiveRoomVisualPropertyEditor({style,device,onChange,onReset}:Props){
 const groups=useMemo(()=>Object.entries(VISUAL_GROUP_LABELS).map(([key,label])=>({key,label,controls:LIVE_ROOM_VISUAL_CONTROLS.filter(c=>c.group===key)})),[]);
 const input=(c:VisualControl)=>{const value=read(style,c.key);if(c.kind==="color")return <input aria-label={c.label} type="color" value={value.startsWith("#")?value:"#000000"} onChange={e=>onChange(c.key,e.target.value)} className="h-8 w-full rounded border bg-background p-1"/>;if(c.kind==="select")return <select aria-label={c.label} value={value} onChange={e=>onChange(c.key,e.target.value)} className={fieldClass}><option value="">Default</option>{c.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>;if(c.kind==="number")return <input aria-label={c.label} type="number" value={value} onChange={e=>onChange(c.key,coerceVisualValue(c,e.target.value))} className={fieldClass}/>;return <input aria-label={c.label} value={value} onChange={e=>onChange(c.key,e.target.value)} className={fieldClass}/>};
 return <div className="space-y-3">
  <div className="flex items-center justify-between"><div className="text-xs font-semibold"><Paintbrush className="mr-1 inline h-3.5 w-3.5"/>Visual Properties</div><span className="text-[9px] text-muted-foreground">{device}</span></div>
  {groups.map(g=><details key={g.key} open className="rounded-lg border"><summary className="cursor-pointer px-3 py-2 text-[10px] font-bold uppercase tracking-wide">{g.label}</summary><div className="grid grid-cols-2 gap-2 border-t p-2">{g.controls.map(c=><label key={c.key} className="text-[9px] text-muted-foreground">{c.label}{input(c)}</label>)}</div></details>)}
  <details className="rounded-lg border"><summary className="cursor-pointer px-3 py-2 text-[10px] font-bold uppercase tracking-wide">Gradient</summary><div className="grid gap-2 border-t p-2"><label className="text-[9px] text-muted-foreground">Background gradient<input value={read(style,"backgroundImage")} onChange={e=>onChange("backgroundImage",e.target.value)} placeholder="linear-gradient(...)" className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Background position<input value={read(style,"backgroundPosition")} onChange={e=>onChange("backgroundPosition",e.target.value)} placeholder="center" className={fieldClass}/></label></div></details>
  <details className="rounded-lg border"><summary className="cursor-pointer px-3 py-2 text-[10px] font-bold uppercase tracking-wide">Radius & Shadow</summary><div className="grid grid-cols-2 gap-2 border-t p-2"><label className="text-[9px] text-muted-foreground">Top-left<input value={read(style,"borderTopLeftRadius")} onChange={e=>onChange("borderTopLeftRadius",e.target.value)} className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Top-right<input value={read(style,"borderTopRightRadius")} onChange={e=>onChange("borderTopRightRadius",e.target.value)} className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Bottom-right<input value={read(style,"borderBottomRightRadius")} onChange={e=>onChange("borderBottomRightRadius",e.target.value)} className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Bottom-left<input value={read(style,"borderBottomLeftRadius")} onChange={e=>onChange("borderBottomLeftRadius",e.target.value)} className={fieldClass}/></label><label className="col-span-2 text-[9px] text-muted-foreground">Box shadow<input value={read(style,"boxShadow")} onChange={e=>onChange("boxShadow",e.target.value)} placeholder="0 8px 24px rgba(...)" className={fieldClass}/></label></div></details>
  <details className="rounded-lg border"><summary className="cursor-pointer px-3 py-2 text-[10px] font-bold uppercase tracking-wide">Animation</summary><div className="grid grid-cols-2 gap-2 border-t p-2"><label className="text-[9px] text-muted-foreground">Animation name<input value={read(style,"animationName")} onChange={e=>onChange("animationName",e.target.value)} placeholder="fadeIn" className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Duration<input value={read(style,"animationDuration")} onChange={e=>onChange("animationDuration",e.target.value)} placeholder="300ms" className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Timing<input value={read(style,"animationTimingFunction")} onChange={e=>onChange("animationTimingFunction",e.target.value)} placeholder="ease" className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Delay<input value={read(style,"animationDelay")} onChange={e=>onChange("animationDelay",e.target.value)} placeholder="0ms" className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Iteration<input value={read(style,"animationIterationCount")} onChange={e=>onChange("animationIterationCount",e.target.value)} placeholder="1" className={fieldClass}/></label><label className="text-[9px] text-muted-foreground">Play state<select value={read(style,"animationPlayState")} onChange={e=>onChange("animationPlayState",e.target.value)} className={fieldClass}><option value="">running</option><option value="running">running</option><option value="paused">paused</option></select></label></div></details>
  <button onClick={()=>onReset(LIVE_ROOM_VISUAL_CONTROLS.map(c=>c.key).concat(["backgroundImage","backgroundPosition","borderTopLeftRadius","borderTopRightRadius","borderBottomRightRadius","borderBottomLeftRadius","boxShadow","animationName","animationDuration","animationTimingFunction","animationDelay","animationIterationCount","animationPlayState"]))} className="w-full rounded-lg border px-3 py-2 text-xs"><RotateCcw className="mr-1 inline h-3.5 w-3.5"/>Reset visual overrides</button>
 </div>;
}
