import { useMemo } from "react";
import type { ComponentStyle, DeviceKind } from "@/lib/app-customization/schema";
import { LIVE_ROOM_VISUAL_CONTROLS, VISUAL_GROUP_LABELS, coerceVisualValue, type VisualControl } from "@/lib/app-customization/live-room-visual-controls";
import { Paintbrush, RotateCcw } from "lucide-react";

export function LiveRoomVisualPropertyEditor({style,device,onChange,onReset}:{style:ComponentStyle;device:DeviceKind;onChange:(key:string,value:unknown)=>void;onReset:(keys:string[])=>void}) {
 const groups=useMemo(()=>Object.entries(VISUAL_GROUP_LABELS).map(([key,label])=>({key,label,controls:LIVE_ROOM_VISUAL_CONTROLS.filter(c=>c.group===key)})),[]);
 const input=(c:VisualControl)=>{const value=String((style as Record<string,unknown>)[c.key]??""); if(c.kind==="color") return <input type="color" value={value.startsWith("#")?value:"#000000"} onChange={e=>onChange(c.key,e.target.value)} className="h-8 w-full rounded border bg-background p-1"/>; if(c.kind==="select") return <select value={value} onChange={e=>onChange(c.key,e.target.value)} className="w-full rounded border bg-background px-2 py-1.5 text-xs"><option value="">Default</option>{c.options?.map(o=><option key={o} value={o}>{o}</option>)}</select>; if(c.kind==="number") return <input type="number" value={value} onChange={e=>onChange(c.key,coerceVisualValue(c,e.target.value))} className="w-full rounded border bg-background px-2 py-1.5 text-xs"/>; return <input value={value} onChange={e=>onChange(c.key,e.target.value)} className="w-full rounded border bg-background px-2 py-1.5 text-xs"/>;};
 return <div className="space-y-3"><div className="flex items-center justify-between"><div className="text-xs font-semibold"><Paintbrush className="mr-1 inline h-3.5 w-3.5"/>Visual Properties</div><span className="text-[9px] text-muted-foreground">{device}</span></div>{groups.map(g=><details key={g.key} open className="rounded-lg border"><summary className="cursor-pointer px-3 py-2 text-[10px] font-bold uppercase tracking-wide">{g.label}</summary><div className="grid grid-cols-2 gap-2 border-t p-2">{g.controls.map(c=><label key={c.key} className="text-[9px] text-muted-foreground">{c.label}{input(c)}</label>)}</div></details>)}<button onClick={()=>onReset(LIVE_ROOM_VISUAL_CONTROLS.map(c=>c.key))} className="w-full rounded-lg border px-3 py-2 text-xs"><RotateCcw className="mr-1 inline h-3.5 w-3.5"/>Reset visual overrides</button></div>;
}
