import { useMemo } from "react";
import type { AppComponentNode, ComponentStyle, DeviceKind } from "@/lib/app-customization/schema";

type Props = { node: AppComponentNode | null; device: DeviceKind; onChange: (patch: Partial<AppComponentNode>) => void };

const inputClass = "w-full rounded-md border border-border bg-background px-2 py-1.5 text-xs outline-none focus:ring-1 focus:ring-primary";
const labelClass = "mb-1 block text-[10px] font-medium uppercase tracking-wide text-muted-foreground";

function num(v: unknown) { return typeof v === "number" ? v : Number.parseFloat(String(v ?? "").replace(/px$/, "")) || 0; }
function updateStyle(node: AppComponentNode, onChange: Props["onChange"], patch: Partial<ComponentStyle>) { onChange({ style: { ...(node.style ?? {}), ...patch } }); }

export function StudioPropertyInspector({ node, device, onChange }: Props) {
  const responsive = useMemo(() => node?.responsive?.[device], [node, device]);
  if (!node) return <aside className="border-l border-border bg-background p-4 text-xs text-muted-foreground">Select an element to edit its properties.</aside>;
  const style = responsive?.style ?? node.style ?? {};
  const set = (key: keyof ComponentStyle, value: string | number) => updateStyle(node, onChange, { [key]: value } as Partial<ComponentStyle>);
  const setResponsive = (patch: Partial<ComponentStyle>) => onChange({ responsive: { ...(node.responsive ?? {}), [device]: { ...(node.responsive?.[device] ?? {}), style: { ...(node.responsive?.[device]?.style ?? {}), ...patch } } } });
  const setBoth = (key: keyof ComponentStyle, value: string | number) => device === "mobile" && !node.responsive?.mobile ? set(key, value) : setResponsive({ [key]: value } as Partial<ComponentStyle>);
  return <aside className="border-l border-border bg-background overflow-y-auto p-3 text-xs">
    <div className="mb-3 flex items-center justify-between"><div><div className="font-semibold">{node.name ?? node.type}</div><div className="text-[10px] text-muted-foreground">{node.type} · {device}</div></div><span className="rounded bg-muted px-1.5 py-1 text-[9px]">{node.id.slice(0, 12)}</span></div>
    <section className="border-b border-border pb-3"><h4 className="mb-2 font-semibold">Design</h4><div className="grid grid-cols-2 gap-2">{(["width","height","x","y","zIndex"] as const).map((key) => <label key={key}><span className={labelClass}>{key}</span><input className={inputClass} value={style[key] == null ? "" : String(style[key])} onChange={e => setBoth(key, key === "zIndex" || key === "x" || key === "y" ? num(e.target.value) : e.target.value)} /></label>)}</div><label className="mt-2 block"><span className={labelClass}>Position</span><select className={inputClass} value={style.position ?? "static"} onChange={e => setBoth("position", e.target.value)}><option>static</option><option>relative</option><option>absolute</option><option>fixed</option><option>sticky</option></select></label></section>
    <section className="border-b border-border py-3"><h4 className="mb-2 font-semibold">Spacing</h4><div className="grid grid-cols-2 gap-2">{(["top","right","bottom","left"] as const).map(key => <label key={key}><span className={labelClass}>{key}</span><input className={inputClass} value={style.spacing?.[key] ?? ""} onChange={e => setBoth("spacing", { ...(style.spacing ?? {}), [key]: e.target.value })} /></label>)}</div><div className="mt-2 grid grid-cols-2 gap-2"><label><span className={labelClass}>Padding</span><input className={inputClass} value={style.padding ?? ""} onChange={e => setBoth("padding", e.target.value)} /></label><label><span className={labelClass}>Margin</span><input className={inputClass} value={style.margin ?? ""} onChange={e => setBoth("margin", e.target.value)} /></label></div></section>
    <section className="border-b border-border py-3"><h4 className="mb-2 font-semibold">Background & Border</h4><div className="grid grid-cols-2 gap-2"><label><span className={labelClass}>Background</span><input className={inputClass} value={style.background ?? ""} onChange={e => setBoth("background", e.target.value)} /></label><label><span className={labelClass}>Text Color</span><input className={inputClass} value={style.color ?? ""} onChange={e => setBoth("color", e.target.value)} /></label><label><span className={labelClass}>Radius</span><input className={inputClass} value={style.borderRadius ?? ""} onChange={e => setBoth("borderRadius", e.target.value)} /></label><label><span className={labelClass}>Opacity</span><input className={inputClass} type="number" min="0" max="1" step=".05" value={style.opacity ?? 1} onChange={e => setBoth("opacity", Number(e.target.value))} /></label></div></section>
    <section className="border-b border-border py-3"><h4 className="mb-2 font-semibold">Typography</h4><div className="grid grid-cols-2 gap-2">{(["fontFamily","fontSize","fontWeight","lineHeight","letterSpacing","textAlign"] as const).map(key => <label key={key}><span className={labelClass}>{key}</span><input className={inputClass} value={style[key] == null ? "" : String(style[key])} onChange={e => setBoth(key, e.target.value)} /></label>)}</div></section>
    {(node.type === "text" || node.type === "heading" || node.type === "paragraph" || node.type === "button") && <section className="py-3"><h4 className="mb-2 font-semibold">Content</h4><textarea className={inputClass + " min-h-20"} value={String(node.props?.text ?? node.props?.label ?? "")} onChange={e => onChange({ props: { ...(node.props ?? {}), text: e.target.value, label: e.target.value } })} placeholder="Visible text" /></section>}
  </aside>;
}
